[global]
error_log = /proc/self/fd/2
daemonize = no

[www]
listen = 9000
clear_env = no
catch_workers_output = yes
decorate_workers_output = no
request_terminate_timeout = 3600s

pm = static
pm.max_children = ${FPM_MAX_CHILDREN}
pm.max_requests = 500
