<?php
			return ["id_rapport" => "all_notes_de_frais",
	"categorie" => "rh",
	"icone" => "table",
	"titre" => "Toutes les notes de frais",
	"description" => "Toutes les notes de frais",
	"type" => "liste_libre",
	"type_rapport" => "liste_libre",
	"parametrage_rapport_libre" => "{\"series\":[{\"nom\":null,\"type_calcul\":null,\"champ_calcul\":null,\"index_traduction\":\"rapport.all_notes_de_frais.serie_0\"}]}",
	"type_element" => "note_de_frais",
	"liste_libre" => [
		"type_element" => "note_de_frais",
		"id_rapport" => "all_notes_de_frais",
		'colonnes' => [
					array("liste_libre_id" => "321", "nom" => "#", "valeur" => "id", "ordre" => "1", "lien_vers_element" => "1", "type" => "standard", ),
						array("liste_libre_id" => "321", "nom" => "Utilisateur", "valeur" => "utilisateur_id", "ordre" => "2", "type" => "standard", ),
						array("liste_libre_id" => "321", "nom" => "Saisi le", "valeur" => "cree_le", "ordre" => "3", "type" => "standard", ),
						array("liste_libre_id" => "321", "nom" => "Date NDF", "valeur" => "date", "ordre" => "4", "type" => "standard", "retour_a_la_ligne_impossible" => "1", ),
						array("liste_libre_id" => "321", "nom" => "Catégorie de dépenses", "valeur" => "article_id", "ordre" => "5", "lien_vers_element" => "1", "type" => "standard", ),
						array("liste_libre_id" => "321", "nom" => "Montant HT", "valeur" => "montant_ht", "ordre" => "6", "lien_vers_element" => "1", "type" => "standard", ),
						array("liste_libre_id" => "321", "nom" => "Total TVA", "valeur" => "total_tva", "ordre" => "7", "type" => "standard", ),
						array("liste_libre_id" => "321", "nom" => "Montant TTC", "valeur" => "montant_ttc", "ordre" => "8", "lien_vers_element" => "1", "type" => "standard", ),
						array("liste_libre_id" => "321", "nom" => "Pré-validé N+1", "valeur" => "#pre_valide_dp# #doublon#", "ordre" => "9", "type" => "concatenation", ),
						array("liste_libre_id" => "321", "nom" => "Date prévi. remboursement", "valeur" => "date_previ_remboursement", "ordre" => "10", "type" => "standard", ),
						array("liste_libre_id" => "321", "nom" => "Remboursée", "ordre" => "11", "type" => "champ", "champ" => "rembourse", ),
						array("liste_libre_id" => "321", "nom" => "Montant Remboursé", "ordre" => "12", "type" => "champ", "champ" => "montant_rembourse", ),
						array("liste_libre_id" => "321", "nom" => "DATE REELLE REMBOURSEMENT", "ordre" => "13", "type" => "champ", "champ" => "date_reelle_de_remboursement", ),
						array("liste_libre_id" => "321", "nom" => "CB Entreprise", "valeur" => "cb_entreprise", "ordre" => "14", "type" => "standard", ),
						array("liste_libre_id" => "321", "nom" => "Tags", "ordre" => "15", "methode" => "tags_pour_liste", "tri_desactive" => "1", "type" => "methode", "retour_a_la_ligne_impossible" => "1", ),
						array("liste_libre_id" => "321", "nom" => "Commentaire", "valeur" => "commentaire", "ordre" => "16", "type" => "standard", ),
						array("liste_libre_id" => "321", "nom" => "Justificatif", "valeur" => "scan", "ordre" => "17", "type" => "standard", "retour_a_la_ligne_impossible" => "1", ),
						],
				'calculs' => [
					array("liste_libre_id" => "321", "nom_sql" => "montant_ttc", "type_calcul" => "SUM", "nom" => "Total TTC", "unite" => "€", "ordre" => "1", ),
						array("liste_libre_id" => "321", "nom_sql" => "montant_rembourse", "type_calcul" => "SUM", "nom" => "Total remboursée TTC", "unite" => "€", "ordre" => "2", ),
						],
				'filtres' => [
					array("liste_libre_id" => "321", "nom_sql" => "date", "ordre" => "1", ),
						array("liste_libre_id" => "321", "nom_sql" => "utilisateur_id", "ordre" => "2", ),
						array("liste_libre_id" => "321", "nom_sql" => "accepte", "ordre" => "3", ),
						array("liste_libre_id" => "321", "nom_sql" => "comptabilisee", "ordre" => "4", ),
						array("liste_libre_id" => "321", "nom_sql" => "rembourse", "ordre" => "5", ),
						array("liste_libre_id" => "321", "nom_sql" => "pre_valide_dp", "ordre" => "6", ),
						array("liste_libre_id" => "321", "nom_sql" => "article_id", "ordre" => "7", ),
						array("liste_libre_id" => "321", "nom_sql" => "cb_entreprise", "ordre" => "8", ),
						array("liste_libre_id" => "321", "nom_sql" => "date_reelle_de_remboursement", "ordre" => "9", ),
						array("liste_libre_id" => "321", "nom_sql" => "doublon", "ordre" => "10", ),
						],
				]];