<?php
return [
    "colonnes" => [
        array("nom" => "Famille", "valeur" => "famille_id", "ordre" => "1", "lien_vers_element" => "1", "methode" => "", "lien_vers_autre_element" => null, "tri_desactive" => "",  "profils" => '', "type" => "standard", "champ" => "", "responsive" => "", "caracteres_max" => "", "standard" => "", "retour_a_la_ligne_impossible" => "", "couleur_colonne" => "",  "alignement_colonne" => "", "tri_par_defaut" => "", "sens_tri_par_defaut" => "", "arguments" => "", ),
        array("nom" => "Article", "valeur" => "article_id", "ordre" => "2", "lien_vers_element" => "1", "methode" => "", "lien_vers_autre_element" => null, "tri_desactive" => "",  "profils" => '', "type" => "standard", "champ" => "", "responsive" => "", "caracteres_max" => "", "standard" => "", "retour_a_la_ligne_impossible" => "", "couleur_colonne" => "",  "alignement_colonne" => "", "tri_par_defaut" => "", "sens_tri_par_defaut" => "", "arguments" => "", ),
        array("nom" => "Article f.", "valeur" => "article_fournisseur_id", "ordre" => "3", "lien_vers_element" => "1"),
        array("nom" => "Client", "valeur" => "client_id", "ordre" => "4", "lien_vers_element" => "1", "methode" => "", "lien_vers_autre_element" => null, "tri_desactive" => "",  "profils" => '', "type" => "standard", "champ" => "", "responsive" => "", "caracteres_max" => "", "standard" => "", "retour_a_la_ligne_impossible" => "", "couleur_colonne" => "",  "alignement_colonne" => "", "tri_par_defaut" => "", "sens_tri_par_defaut" => "", "arguments" => "", ),
        array("nom" => "Catalogue tarif", "valeur" => "catalogue_tarif_id", "ordre" => "5", "lien_vers_element" => "1", "methode" => "", "lien_vers_autre_element" => null, "tri_desactive" => "",  "profils" => '', "type" => "standard", "champ" => "", "responsive" => "", "caracteres_max" => "", "standard" => "", "retour_a_la_ligne_impossible" => "", "couleur_colonne" => "",  "alignement_colonne" => "", "tri_par_defaut" => "", "sens_tri_par_defaut" => "", "arguments" => "", ),
        array("nom" => "Conditionnement", "valeur" => "conditionnement", "ordre" => "6", "lien_vers_element" => "", "methode" => "", "lien_vers_autre_element" => null, "tri_desactive" => "",  "profils" => '', "type" => "standard", "champ" => "", "responsive" => "", "caracteres_max" => "", "standard" => "", "retour_a_la_ligne_impossible" => "", "couleur_colonne" => "",  "alignement_colonne" => "", "tri_par_defaut" => "", "sens_tri_par_defaut" => "", "arguments" => "", ),
        array("nom" => "Palier de quantité", "valeur" => "palier_quantite", "ordre" => "7", "lien_vers_element" => "", "methode" => "", "lien_vers_autre_element" => null, "tri_desactive" => "",  "profils" => '', "type" => "standard", "champ" => "", "responsive" => "", "caracteres_max" => "", "standard" => "", "retour_a_la_ligne_impossible" => "", "couleur_colonne" => "",  "alignement_colonne" => "", "tri_par_defaut" => "", "sens_tri_par_defaut" => "", "arguments" => "", ),
        array("nom" => "Tarif", "valeur" => "tarif", "ordre" => "8", "lien_vers_element" => "", "methode" => "", "lien_vers_autre_element" => null, "tri_desactive" => "",  "profils" => '', "type" => "standard", "champ" => "", "responsive" => "", "caracteres_max" => "", "standard" => "", "retour_a_la_ligne_impossible" => "", "couleur_colonne" => "",  "alignement_colonne" => "", "tri_par_defaut" => "", "sens_tri_par_defaut" => "", "arguments" => "", ),
        array("nom" => "Remise", "valeur" => "remise", "ordre" => "9", "lien_vers_element" => "", "methode" => "", "lien_vers_autre_element" => null, "tri_desactive" => "",  "profils" => '', "type" => "standard", "champ" => "", "responsive" => "", "caracteres_max" => "", "standard" => "", "retour_a_la_ligne_impossible" => "", "couleur_colonne" => "",  "alignement_colonne" => "", "tri_par_defaut" => "", "sens_tri_par_defaut" => "", "arguments" => "", ),
        array("nom" => "Prix achat", "valeur" => "prix_achat", "ordre" => "10", "lien_vers_element" => "", "methode" => "", "lien_vers_autre_element" => null, "tri_desactive" => "",  "profils" => '', "type" => "standard", "champ" => "", "responsive" => "", "caracteres_max" => "", "standard" => "", "retour_a_la_ligne_impossible" => "", "couleur_colonne" => "",  "alignement_colonne" => "", "tri_par_defaut" => "", "sens_tri_par_defaut" => "", "arguments" => "", ),
    ],
    'calculs' => [
    ],
    'filtres' => [
    ],
];