<?php

return [
		'table_libre' => [
			'nom_table' => "stocks",
			'nom_table_sql' => "stocks",
			'element' => "stocks",
			'type_element' => "stocks",
			'element_pluriel' => "stocks",
			'vue_sql' => "1",
            'creation_rapide' => 0,
            'fiche' => 0,
            
            'disponible_recherche_rapide' => 0,
		],
		'champs_libres' => [
			'famille_id' => [
				'type_element' => "stocks",
				'nom' => "Famille",
				'nom_sql' => "famille_id",
				'type' => "20",
				'liste_choix' => "2",
				'recherche' => "1",
				'obligatoire' => "1",
				'type_element_origine' => "article",
				'nom_sql_origine' => "famille_id",
			],
			'entrepot_id' => [
				'type_element' => "stocks",
				'nom' => "Entrepot id",
				'nom_sql' => "entrepot_id",
				'type' => "20",
				'liste_choix' => "8",
				'type_element_origine' => "mouvement_de_stock",
				'nom_sql_origine' => "entrepot_id",
			],
			'stock_actuel' => [
				'type_element' => "stocks",
				'nom' => "Stock actuel",
				'nom_sql' => "stock_actuel",
				'type' => "3",
				'obligatoire' => "1",
				'type_element_origine' => "mouvement_de_stock",
				'nom_sql_origine' => "quantite",
			],
			'stock_reserve' => [
				'type_element' => "stocks",
				'nom' => "Stock reserve",
				'nom_sql' => "stock_reserve",
				'type' => "3",
				'obligatoire' => "1",
				'type_element_origine' => "mouvement_de_stock",
				'nom_sql_origine' => "quantite",
			],
			'stock_disponible' => [
				'type_element' => "stocks",
				'nom' => "Stock disponible",
				'nom_sql' => "stock_disponible",
				'type' => "3",
				'obligatoire' => "1",
				'type_element_origine' => "mouvement_de_stock",
				'nom_sql_origine' => "quantite",
			],
			'stock_achete' => [
				'type_element' => "stocks",
				'nom' => "Stock achete",
				'nom_sql' => "stock_achete",
				'type' => "3",
				'obligatoire' => "1",
				'type_element_origine' => "mouvement_de_stock",
				'nom_sql_origine' => "quantite",
			],
			'stock_a_terme' => [
				'type_element' => "stocks",
				'nom' => "Stock a terme",
				'nom_sql' => "stock_a_terme",
				'type' => "3",
				'obligatoire' => "1",
				'type_element_origine' => "mouvement_de_stock",
				'nom_sql_origine' => "quantite",
			],
			'valorisation_stock_actuel' => [
				'type_element' => "stocks",
				'nom' => "Valorisation stock actuel",
				'nom_sql' => "valorisation_stock_actuel",
				'type' => "3",
				'obligatoire' => "1",
				'type_element_origine' => "mouvement_de_stock",
				'nom_sql_origine' => "quantite",
			],
			'rotation_90j' => [
				'type_element' => "stocks",
				'nom' => "Rotation 90j",
				'nom_sql' => "rotation_90j",
				'type' => "3",
				'obligatoire' => "1",
				'type_element_origine' => "mouvement_de_stock",
				'nom_sql_origine' => "quantite",
			],
			'rotation_365j' => [
				'type_element' => "stocks",
				'nom' => "Rotation 365j",
				'nom_sql' => "rotation_365j",
				'type' => "3",
				'obligatoire' => "1",
				'type_element_origine' => "mouvement_de_stock",
				'nom_sql_origine' => "quantite",
			],
			'seuil_mini' => [
				'type_element' => "stocks",
				'nom' => "Seuil mini",
				'nom_sql' => "seuil_mini",
                'type' => "3",
				'type_element_origine' => "seuil_article",
				'nom_sql_origine' => "seuil_mini",
			],
			'seuil_alerte' => [
				'type_element' => "stocks",
				'nom' => "Seuil alerte",
				'nom_sql' => "seuil_alerte",
				'type' => "3",
				'type_element_origine' => "seuil_article",
				'nom_sql_origine' => "seuil_alerte",
			],
			'article_id' => [
				'type_element' => "stocks",
				'nom' => "Article id",
				'nom_sql' => "article_id",
				'type' => "42",
				'recherche' => "1",
				'type_element_ajax' => "article",
				'type_element_origine' => "mouvement_de_stock",
				'nom_sql_origine' => "article_id",
			],
			'fournisseur_id' => [
				'type_element' => "stocks",
				'nom' => "Fournisseur",
				'nom_sql' => "fournisseur_id",
				'type' => "42",
				'type_element_ajax' => "fournisseur",
				'type_element_origine' => "article",
				'nom_sql_origine' => "fournisseur_id",
			],
			'adressage' => [
				'type_element' => "stocks",
				'nom' => "Adressage",
				'nom_sql' => "adressage",
				'type_element_origine' => "stock_initial",
				'nom_sql_origine' => "adressage",
			],
            'quantite_conditionnement' => [
                'type_element' => "stocks",
                'nom' => "Stock initial",
                'nom_sql' => "quantite_conditionnement",
                'type_element_origine' => "stock_initial",
                'nom_sql_origine' => "quantite_conditionnement",
                'type' => 3,
            ],
		],
	];
