<?php

return [
    'table_libre' => [
        'nom_table' => "stocks_tous_les_entrepots_par_conditionnement",
        'nom_table_sql' => "stocks_tous_les_entrepots_par_conditionnement",
        'element' => "stocks_tous_les_entrepots_par_conditionnement",
        'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
        'element_pluriel' => "stocks_tous_les_entrepots_par_conditionnement",
        'creation_rapide' => 0,
        'fiche' => 0,
        
        'disponible_recherche_rapide' => 0,
        'vue_sql' => "1",
    ],
    'champs_libres' => [
        'famille_id' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Famille",
            'nom_sql' => "famille_id",
            'type' => "20",
            'liste_choix' => "2",
            'recherche' => "1",
            'obligatoire' => "1",
            'type_element_origine' => "article",
            'nom_sql_origine' => "famille_id",
        ],
        'stock_actuel' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Stock actuel",
            'nom_sql' => "stock_actuel",
            'type' => "3",
            'obligatoire' => "1",
        ],
        'stock_reserve' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Stock reserve",
            'nom_sql' => "stock_reserve",
            'type' => "3",
            'obligatoire' => "1",
        ],
        'stock_disponible' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Stock disponible",
            'nom_sql' => "stock_disponible",
            'type' => "3",
            'obligatoire' => "1",
            'type_element_origine' => "mouvement_de_stock",
            'nom_sql_origine' => "quantite",
        ],
        'stock_achete' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Stock achete",
            'nom_sql' => "stock_achete",
            'type' => "3",
            'obligatoire' => "1",
            'type_element_origine' => "mouvement_de_stock",
            'nom_sql_origine' => "quantite",
        ],
        'stock_a_terme' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Stock a terme",
            'nom_sql' => "stock_a_terme",
            'type' => "3",
            'obligatoire' => "1",
            'type_element_origine' => "mouvement_de_stock",
            'nom_sql_origine' => "quantite",
        ],
        'valorisation_stock_actuel' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Valorisation stock actuel",
            'nom_sql' => "valorisation_stock_actuel",
            'type' => "3",
            'obligatoire' => "1",
            'type_element_origine' => "mouvement_de_stock",
            'nom_sql_origine' => "quantite",
        ],
        'rotation_90j' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Rotation 90j",
            'nom_sql' => "rotation_90j",
            'type' => "3",
            'obligatoire' => "1",
            'type_element_origine' => "mouvement_de_stock",
            'nom_sql_origine' => "quantite",
        ],
        'rotation_365j' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Rotation 365j",
            'nom_sql' => "rotation_365j",
            'type' => "3",
            'obligatoire' => "1",
            'type_element_origine' => "mouvement_de_stock",
            'nom_sql_origine' => "quantite",
        ],
        'stock_actuel_conditionnement' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Stock actuel conditionnement",
            'nom_sql' => "stock_actuel_conditionnement",
            'type' => "3",
            'obligatoire' => "1",
            'type_element_origine' => "mouvement_de_stock",
            'nom_sql_origine' => "quantite",
        ],
        'stock_reserve_conditionnement' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Stock reserve conditionnement",
            'nom_sql' => "stock_reserve_conditionnement",
            'type' => "3",
            'obligatoire' => "1",
            'type_element_origine' => "mouvement_de_stock",
            'nom_sql_origine' => "quantite",
        ],
        'stock_disponible_conditionnement' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Stock disponible conditionnement",
            'nom_sql' => "stock_disponible_conditionnement",
            'type' => "3",
            'obligatoire' => "1",
            'type_element_origine' => "mouvement_de_stock",
            'nom_sql_origine' => "quantite",
        ],
        'stock_achete_conditionnement' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Stock achete conditionnement",
            'nom_sql' => "stock_achete_conditionnement",
            'type' => "3",
            'obligatoire' => "1",
            'type_element_origine' => "mouvement_de_stock",
            'nom_sql_origine' => "quantite",
        ],
        'stock_a_terme_conditionnement' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Stock a terme conditionnement",
            'nom_sql' => "stock_a_terme_conditionnement",
            'type' => "3",
            'obligatoire' => "1",
            'type_element_origine' => "mouvement_de_stock",
            'nom_sql_origine' => "quantite",
        ],
        'valorisation_stock_actuel_conditionnement' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Valorisation stock actuel conditionnement",
            'nom_sql' => "valorisation_stock_actuel_conditionnement",
            'type' => "3",
            'obligatoire' => "1",
            'type_element_origine' => "mouvement_de_stock",
            'nom_sql_origine' => "quantite",
        ],
        'rotation_90j_conditionnement' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Rotation 90j conditionnement",
            'nom_sql' => "rotation_90j_conditionnement",
            'type' => "3",
            'obligatoire' => "1",
            'type_element_origine' => "mouvement_de_stock",
            'nom_sql_origine' => "quantite",
        ],
        'rotation_365j_conditionnement' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Rotation 365j conditionnement",
            'nom_sql' => "rotation_365j_conditionnement",
            'type' => "3",
            'obligatoire' => "1",
            'type_element_origine' => "mouvement_de_stock",
            'nom_sql_origine' => "quantite",
        ],
        'seuil_mini' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Seuil mini",
            'nom_sql' => "seuil_mini",
            'type' => "3",
            'type_element_origine' => "seuil_article",
            'nom_sql_origine' => "seuil_mini",
        ],
        'seuil_mini_unite' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Seuil mini unite",
            'nom_sql' => "seuil_mini_unite",
            'type' => "3",
            'type_element_origine' => "seuil_article",
            'nom_sql_origine' => "seuil_mini",
        ],
        'seuil_alerte' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Seuil alerte",
            'nom_sql' => "seuil_alerte",
            'type' => "3",
            'type_element_origine' => "seuil_article",
            'nom_sql_origine' => "seuil_alerte",
        ],
        'seuil_alerte_unite' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Seuil alerte unite",
            'nom_sql' => "seuil_alerte_unite",
            'type' => "3",
            'type_element_origine' => "seuil_article",
            'nom_sql_origine' => "seuil_alerte",
        ],
        'article_id' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Article id",
            'nom_sql' => "article_id",
            'type' => "42",
            'recherche' => "1",
            'type_element_origine' => "mouvement_de_stock",
            'nom_sql_origine' => "article_id",
        ],
        'fournisseur_id' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Fournisseur",
            'nom_sql' => "fournisseur_id",
            'type' => "42",
            'type_element_ajax' => "fournisseur",
            'type_element_origine' => "article",
            'nom_sql_origine' => "fournisseur_id",
        ],
        'conditionnement_id' => [
            'type_element' => "stocks_tous_les_entrepots_par_conditionnement",
            'nom' => "Conditionnement id",
            'nom_sql' => "conditionnement_id",
            'type' => "42",
            'type_element_ajax' => "conditionnement",
            'type_element_origine' => "stock_initial",
            'nom_sql_origine' => "conditionnement_id",

        ],
    ],
];
