<?php 
    return [
        'nom' => 'union_facture_avoir_negatif',
        'nom_sql' => 'union_facture_avoir_negatif',
        'joins' => '',
        'tables' => '',
        'alias_tables' => '',
        'table_par_defaut' => '',
        'type_de_vue' => '1',
        'requete' => 'CREATE OR REPLACE VIEW union_facture_avoir_negatif AS 
            select 
            \'facture\' AS type_document,
            #colonnes_eden#,
            modifie_par,
            modifie_le,
            cree_par,
            cree_le,
            inactif,
            date,
            mode_paiement_id,
            projet_id,
            reference_document,
            date_de_reglement,
            objet,
            entite_id,
            client_id,
            montant_document_ht,
            montant_document_ttc,
            montant_document_tva,
            solde_document_ttc,
            frais_de_livraison,
            comptabilise,
            valide,
            regle,
            canal,
            client_livraison_id,
            adresse_de_livraison,
            adresse_de_facturation,
            remise_globale,
            remise_globale_type,
            responsable_commercial_id,
            statut,
            marge 
        from facture_vente

        union
        
        select 
            \'avoir\' AS type_document,
            #colonnes_eden#,
            modifie_par,
            modifie_le,
            cree_par,
            cree_le,
            inactif,
            date,
            mode_paiement_id,
            projet_id,
            reference_document,
            date_de_reglement,
            objet,
            entite_id,
            client_id,
            montant_document_ht * -1,
            montant_document_ttc * -1,
            montant_document_tva * -1,
            solde_document_ttc * -1,
            frais_de_livraison,
            comptabilise,
            valide,
            regle,
            canal,
            client_livraison_id,
            adresse_de_livraison,
            adresse_de_facturation,
            remise_globale,
            remise_globale_type,
            responsable_commercial_id,
            statut,
            marge * -1
        from avoir_vente',
        'autres_conditions' => '',
    ];