<?php 
    return [
        'nom' => 'union_acompte_facture_avoir_vente',
        'nom_sql' => 'union_acompte_facture_avoir_vente',
        'joins' => '',
        'tables' => '',
        'alias_tables' => '',
        'table_par_defaut' => '',
        'type_de_vue' => '1',
        'requete' => 'CREATE OR REPLACE VIEW union_acompte_facture_avoir_vente AS 
        select 
            \'facture\' AS type_document,
            facture_vente.id,facture_vente.chaine_tags_recherche,
            facture_vente.id as id_document,
            facture_vente.modifie_par,
            facture_vente.modifie_le,
            facture_vente.cree_par,
            facture_vente.cree_le,
            facture_vente.inactif,
            facture_vente.date,
            facture_vente.mode_paiement_id,
            facture_vente.projet_id,
            facture_vente.reference_document,
            facture_vente.date_de_reglement,
            facture_vente.objet,
            facture_vente.entite_id,
            facture_vente.client_id,
            facture_vente.montant_document_ht,
            facture_vente.montant_document_ttc,
            facture_vente.montant_document_tva,
            facture_vente.solde_document_ttc,
            facture_vente.frais_de_livraison,
            facture_vente.comptabilise,
            facture_vente.valide,
            facture_vente.regle,
            facture_vente.canal,
            facture_vente.client_livraison_id,
            facture_vente.adresse_de_livraison,
            facture_vente.adresse_de_facturation,
            facture_vente.remise_globale,
            facture_vente.remise_globale_type,
            facture_vente.responsable_commercial_id,
            facture_vente.statut,
            facture_vente.marge, 
            sum(paiement.montant) as montant_regle
        from facture_vente, paiement where paiement.type_element=\'facture_vente\' and paiement.id_document=facture_vente.id and (paiement.inactif is null or paiement.inactif = 0) group by paiement.id_document

        union
        
        select 
            \'acompte\' AS type_document,
            acompte_vente.id,acompte_vente.chaine_tags_recherche,
            acompte_vente.id as id_document,
            acompte_vente.modifie_par,
            acompte_vente.modifie_le,
            acompte_vente.cree_par,
            acompte_vente.cree_le,
            acompte_vente.inactif,
            acompte_vente.date,
            acompte_vente.mode_paiement_id,
            acompte_vente.projet_id,
            acompte_vente.reference_document,
            acompte_vente.date_de_reglement,
            acompte_vente.objet,
            acompte_vente.entite_id,
            acompte_vente.client_id,
            acompte_vente.montant_document_ht,
            acompte_vente.montant_document_ttc,
            acompte_vente.montant_document_tva,
            acompte_vente.solde_document_ttc,
            acompte_vente.frais_de_livraison,
            acompte_vente.comptabilise,
            acompte_vente.valide,
            acompte_vente.regle,
            acompte_vente.canal,
            acompte_vente.client_livraison_id,
            acompte_vente.adresse_de_livraison,
            acompte_vente.adresse_de_facturation,
            acompte_vente.remise_globale,
            acompte_vente.remise_globale_type,
            acompte_vente.responsable_commercial_id,
            acompte_vente.statut,
            acompte_vente.marge, 
            sum(paiement.montant) as montant_regle
        from acompte_vente, paiement where paiement.type_element=\'acompte_vente\' and paiement.id_document=acompte_vente.id and (paiement.inactif is null or paiement.inactif = 0) group by paiement.id_document

        union
        
        select 
            \'avoir\' AS type_document,
            avoir_vente.id,avoir_vente.chaine_tags_recherche,
            avoir_vente.id as id_document,
            avoir_vente.modifie_par,
            avoir_vente.modifie_le,
            avoir_vente.cree_par,
            avoir_vente.cree_le,
            avoir_vente.inactif,
            avoir_vente.date,
            avoir_vente.mode_paiement_id,
            avoir_vente.projet_id,
            avoir_vente.reference_document,
            avoir_vente.date_de_reglement,
            avoir_vente.objet,
            avoir_vente.entite_id,
            avoir_vente.client_id,
            avoir_vente.montant_document_ht * -1,
            avoir_vente.montant_document_ttc * -1,
            avoir_vente.montant_document_tva * -1,
            avoir_vente.solde_document_ttc * -1,
            avoir_vente.frais_de_livraison,
            avoir_vente.comptabilise,
            avoir_vente.valide,
            avoir_vente.regle,
            avoir_vente.canal,
            avoir_vente.client_livraison_id,
            avoir_vente.adresse_de_livraison,
            avoir_vente.adresse_de_facturation,
            avoir_vente.remise_globale,
            avoir_vente.remise_globale_type,
            avoir_vente.responsable_commercial_id,
            avoir_vente.statut,
            avoir_vente.marge * -1, 
            sum(paiement.montant) as montant_regle
        from avoir_vente, paiement where paiement.type_element=\'avoir_vente\' and paiement.id_document=avoir_vente.id and (paiement.inactif is null or paiement.inactif = 0) group by paiement.id_document',
        'autres_conditions' => '',
    ];