<?php 
    return [
        'nom' => 'union_facture_ligne_avoir_ligne_negatif',
        'nom_sql' => 'union_facture_ligne_avoir_ligne_negatif',
        'joins' => '',
        'tables' => '',
        'alias_tables' => '',
        'table_par_defaut' => '',
        'type_de_vue' => '1',
        'requete' => 'CREATE OR REPLACE VIEW union_facture_ligne_avoir_ligne_negatif AS 
            select 
            \'facture\' AS type_ligne,
            facture_vente_lignes.id,
            facture_vente_lignes.chaine_tags_recherche,
            facture_vente_lignes.modifie_par,
            facture_vente_lignes.modifie_le,
            facture_vente_lignes.cree_par,
            facture_vente_lignes.cree_le,
            article_id,
            quantite,
            tarif,
            remise,
            tva,
            type_tarif,
            remise_globale_ligne,
            tarif_saisi,
            prix_achat,
            unite,
            tarif_apres_remise,
            tarif_net,
            coefficient,
            coefficient_article,
            coefficient_regroupement,
            total,
            tarif_force,
            date,
            montant_document_ht,
            montant_document_ttc,
            montant_document_tva,
            solde_document_ttc,
            frais_de_livraison,
            comptabilise,
            facture_vente.valide,
            regle,
            canal,
            client_livraison_id,
            adresse_de_livraison,
            adresse_de_facturation,
            remise_globale,
            remise_globale_type,
            responsable_commercial_id,
            statut,
            marge
            
        from facture_vente_lignes
        join facture_vente ON facture_vente.id = facture_vente_lignes.document_id

        union
        
        select 
            \'avoir\' AS type_ligne,
            avoir_vente_lignes.id,
            avoir_vente_lignes.chaine_tags_recherche,
            avoir_vente_lignes.modifie_par,
            avoir_vente_lignes.modifie_le,
            avoir_vente_lignes.cree_par,
            avoir_vente_lignes.cree_le,
            article_id,
            quantite,
            tarif * -1,
            remise,
            tva,
            type_tarif,
            remise_globale_ligne,
            tarif_saisi * -1,
            prix_achat * -1,
            unite,
            tarif_apres_remise * -1, 
            tarif_net * -1,
            coefficient,
            coefficient_article,
            coefficient_regroupement,
            total * -1,
            tarif_force * -1,
            date,
            montant_document_ht * -1,
            montant_document_ttc * -1,
            montant_document_tva * -1,
            solde_document_ttc * -1,
            frais_de_livraison,
            comptabilise,
            avoir_vente.valide,
            regle,
            canal,
            client_livraison_id,
            adresse_de_livraison,
            adresse_de_facturation,
            remise_globale,
            remise_globale_type,
            responsable_commercial_id,
            statut,
            marge * -1
        from avoir_vente_lignes
        join avoir_vente ON avoir_vente.id = avoir_vente_lignes.document_id',
        'autres_conditions' => '',
    ];