<?php
return [
        'vue_js' => [
            'vuejs_data' => "",
            'vuejs_methods' => "",
            'surcharger_la_vue' => "",
        ],
        'champs_libres' => [
            [
                'type_element' => "activite",
                'nom_sql' => "type_element",
                'taille_avant' => "0",
                'taille_libelle' => "2",
                'taille_champ' => "4",
                'taille_apres' => "0",
                'ordre' => "1",

            ],
            [
                'type_element' => "activite",
                'nom_sql' => "element_id",
                'taille_avant' => "0",
                'taille_libelle' => "2",
                'taille_champ' => "4",
                'taille_apres' => "0",
                'ordre' => "2",
            ],
            [
                'type_element' => "activite",
                'nom_sql' => "categorie_activite_id",
                'taille_avant' => "0",
                'taille_libelle' => "2",
                'taille_champ' => "4",
                'taille_apres' => "6",
                'ordre' => "3",
            ],
            [
                'type_element' => "activite",
                'nom_sql' => "activite",
                'taille_avant' => "0",
                'taille_libelle' => "2",
                'taille_champ' => "4",
                'taille_apres' => "6",
                'ordre' => "4",
            ],
            [
                'type_element' => "activite",
                'nom_sql' => "utilisateurs_id",
                'taille_avant' => "0",
                'taille_libelle' => "2",
                'taille_champ' => "4",
                'taille_apres' => "6",
                'ordre' => "5",
            ],
            [
                'type_element' => "activite",
                'nom_sql' => "vendu",
                'taille_avant' => "0",
                'taille_libelle' => "2",
                'taille_champ' => "4",
                'taille_apres' => "0",
                'ordre' => "6",
            ],
            [
                'type_element' => "activite",
                'nom_sql' => "previsionnel",
                'taille_avant' => "0",
                'taille_libelle' => "2",
                'taille_champ' => "4",
                'taille_apres' => "0",
                'ordre' => "7",
            ],
            [
                'type_element' => "activite",
                'nom_sql' => "prioritaire",
                'taille_avant' => "0",
                'taille_libelle' => "2",
                'taille_champ' => "4",
                'taille_apres' => "0",
                'ordre' => "8",
            ],
            [
                'type_element' => "activite",
                'nom_sql' => "article_id",
                'taille_avant' => "0",
                'taille_libelle' => "2",
                'taille_champ' => "4",
                'taille_apres' => "0",
                'ordre' => "9",
            ],
            [
                'type_element' => "activite",
                'nom_sql' => "tarif",
                'taille_avant' => "0",
                'taille_libelle' => "2",
                'taille_champ' => "4",
                'taille_apres' => "0",
                'ordre' => "10",
                'condition_affichage_v_if' => 'activite.article_id > 0',
            ],
            [
                'type_element' => "activite",
                'nom_sql' => "remise_pourcentage",
                'taille_avant' => "0",
                'taille_libelle' => "2",
                'taille_champ' => "4",
                'taille_apres' => "0",
                'ordre' => "11",
                'condition_affichage_v_if' => 'activite.article_id > 0',
            ],
        ],
    ];