<?php

return [
	'vue_js' => [
		'vuejs_data' => "",
		'vuejs_methods' => "",
		'surcharger_la_vue' => "",
	],
	'champs_libres' => [
		[
			'nom_formulaire' => 'annuaire_facturation',
			'type_element' => 'annuaire_facturation',
			'nom_sql' => 'client_id',
			'taille_avant' => '0',
			'taille_libelle' => '2',
			'taille_champ' => '4',
			'taille_apres' => '6',
			'ordre' => '1',
			'type_champ' => '',
			'valeur_html' => '',
			'id_editeur' => '',
			'profils' => '',
			'type_vue' => '',
			'nom_vue' => '',
			'condition_obligatoire' => '',
			'condition_lecture_seule' => '',
			'condition_affichage_v_if' => "annuaire_facturation.client_id > 0 || !(annuaire_facturation.fournisseur_id > 0)",
			'id_sous_formulaire' => '',
			'nom_sous_formulaire' => '',
			'nom_affichage_sous_formulaire' => '',
		],
		[
			'nom_formulaire' => 'annuaire_facturation',
			'type_element' => 'annuaire_facturation',
			'nom_sql' => 'fournisseur_id',
			'taille_avant' => '0',
			'taille_libelle' => '2',
			'taille_champ' => '4',
			'taille_apres' => '6',
			'ordre' => '2',
			'type_champ' => '',
			'valeur_html' => '',
			'id_editeur' => '',
			'profils' => '',
			'type_vue' => '',
			'nom_vue' => '',
			'condition_obligatoire' => '',
			'condition_lecture_seule' => '',
			'condition_affichage_v_if' => "annuaire_facturation.fournisseur_id > 0 || !(annuaire_facturation.client_id > 0)",
			'id_sous_formulaire' => '',
			'nom_sous_formulaire' => '',
			'nom_affichage_sous_formulaire' => '',
		],
		[
			'nom_formulaire' => 'annuaire_facturation',
			'type_element' => 'annuaire_facturation',
			'nom_sql' => 'nom',
			'taille_avant' => '0',
			'taille_libelle' => '2',
			'taille_champ' => '4',
			'taille_apres' => '6',
			'ordre' => '3',
			'type_champ' => '',
			'valeur_html' => '',
			'id_editeur' => '',
			'profils' => '',
			'type_vue' => '',
			'nom_vue' => '',
			'condition_obligatoire' => '',
			'condition_lecture_seule' => '',
			'id_sous_formulaire' => '',
			'nom_sous_formulaire' => '',
			'nom_affichage_sous_formulaire' => '',
		],
		[
			'nom_formulaire' => 'annuaire_facturation',
			'type_element' => 'annuaire_facturation',
			'nom_sql' => 'siren',
			'taille_avant' => '0',
			'taille_libelle' => '2',
			'taille_champ' => '4',
			'taille_apres' => '6',
			'ordre' => '4',
			'type_champ' => '',
			'valeur_html' => '',
			'id_editeur' => '',
			'profils' => '',
			'type_vue' => '',
			'nom_vue' => '',
			'condition_obligatoire' => '',
			'condition_lecture_seule' => '',
			'id_sous_formulaire' => '',
			'nom_sous_formulaire' => '',
			'nom_affichage_sous_formulaire' => '',
		],
		[
			'nom_formulaire' => 'annuaire_facturation',
			'type_element' => 'annuaire_facturation',
			'nom_sql' => 'siret',
			'taille_avant' => '0',
			'taille_libelle' => '2',
			'taille_champ' => '4',
			'taille_apres' => '6',
			'ordre' => '5',
			'type_champ' => '',
			'valeur_html' => '',
			'id_editeur' => '',
			'profils' => '',
			'type_vue' => '',
			'nom_vue' => '',
			'condition_obligatoire' => '',
			'condition_lecture_seule' => '',
			'id_sous_formulaire' => '',
			'nom_sous_formulaire' => '',
			'nom_affichage_sous_formulaire' => '',
		],
		[
			'nom_formulaire' => 'annuaire_facturation',
			'type_element' => 'annuaire_facturation',
			'nom_sql' => 'adressage_id',
			'taille_avant' => '0',
			'taille_libelle' => '2',
			'taille_champ' => '4',
			'taille_apres' => '6',
			'ordre' => '6',
			'type_champ' => '',
			'valeur_html' => '',
			'id_editeur' => '',
			'profils' => '',
			'type_vue' => '',
			'nom_vue' => '',
			'condition_obligatoire' => '',
			'condition_lecture_seule' => '',
			'id_sous_formulaire' => '',
			'nom_sous_formulaire' => '',
			'nom_affichage_sous_formulaire' => '',
		],
		[
			'nom_formulaire' => 'annuaire_facturation',
			'type_element' => 'annuaire_facturation',
			'nom_sql' => 'adressage_suffixe',
			'taille_avant' => '0',
			'taille_libelle' => '2',
			'taille_champ' => '4',
			'taille_apres' => '6',
			'ordre' => '7',
			'type_champ' => '',
			'valeur_html' => '',
			'id_editeur' => '',
			'profils' => '',
			'type_vue' => '',
			'nom_vue' => '',
			'condition_obligatoire' => '',
			'condition_lecture_seule' => '',
			'id_sous_formulaire' => '',
			'nom_sous_formulaire' => '',
			'nom_affichage_sous_formulaire' => '',
		],
		[
			'nom_formulaire' => 'annuaire_facturation',
			'type_element' => 'annuaire_facturation',
			'nom_sql' => 'adresse',
			'taille_avant' => '0',
			'taille_libelle' => '2',
			'taille_champ' => '4',
			'taille_apres' => '6',
			'ordre' => '8',
			'type_champ' => '',
			'valeur_html' => '',
			'id_editeur' => '',
			'profils' => '',
			'type_vue' => '',
			'nom_vue' => '',
			'condition_obligatoire' => '',
			'condition_lecture_seule' => '',
			'id_sous_formulaire' => '',
			'nom_sous_formulaire' => '',
			'nom_affichage_sous_formulaire' => '',
		],
	],
];
