<?php
return [
    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
    ],
    'champs_libres' => [
        [
            'nom_formulaire' => "article_categorie_comptable",
            'type_element' => "article_categorie_comptable",
            'nom_sql' => "article_id",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "0",
            'condition_affichage_v_if' => '!$root.type_element || $root.type_element == \'article\'',
            'condition_obligatoire' => '!$root.type_element || $root.type_element == \'article\'',
        ],
        [
            'nom_formulaire' => "article_categorie_comptable",
            'type_element' => "article_categorie_comptable",
            'nom_sql' => "famille_id",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "1",
            'condition_affichage_v_if' => '!$root.type_element || $root.type_element == \'famille\'',
            'condition_obligatoire' => '!$root.type_element || $root.type_element == \'famille\'',
        ],
        [
            'nom_formulaire' => "article_categorie_comptable",
            'type_element' => "article_categorie_comptable",
            'nom_sql' => "categorie_comptable_id",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "2",

        ],
        [
            'nom_formulaire' => "article_categorie_comptable",
            'type_element' => "article_categorie_comptable",
            'nom_sql' => "compte_produit",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "3",

        ],
        [
            'nom_formulaire' => "article_categorie_comptable",
            'type_element' => "article_categorie_comptable",
            'nom_sql' => "code_tva_id",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "4",

        ],
        [
            'nom_formulaire' => "article_categorie_comptable",
            'type_element' => "article_categorie_comptable",
            'nom_sql' => "compte_charge",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "5",

        ],
        [
            'nom_formulaire' => "article_categorie_comptable",
            'type_element' => "article_categorie_comptable",
            'nom_sql' => "code_tva_achat_id",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "6",

        ],
        [
            'nom_formulaire' => "article_categorie_comptable",
            'type_element' => "article_categorie_comptable",
            'nom_sql' => "",
            'ordre' => 7,
            'taille_avant' => 0,
            'taille_libelle' => 0,
            'taille_champ' => 12,
            'taille_apres' => 0,
            'type_champ' => 2,
            'nom_vue' => "confirmation_enregistrement",
            'type_vue' => "standard",
        ],
    ],
];
