<?php return [

		        'vue_js' => [
		            'vuejs_data' => "",
		            'vuejs_methods' => "",
		            'surcharger_la_vue' => "1",
                ],
                'champs_libres' => [
		[
			'nom_formulaire' => 'article',
				'type_element' => 'article',
				'nom_sql' => 'code_article',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '0',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'article',
				'type_element' => 'article',
				'nom_sql' => 'designation',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '1',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'article',
				'type_element' => 'article',
				'nom_sql' => 'famille_id',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '2',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'article',
				'type_element' => 'article',
				'nom_sql' => 'taux_de_tva',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '3',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'article',
				'type_element' => 'article',
				'nom_sql' => 'disponible_pour_saisie',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '4',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'article',
				'type_element' => 'article',
				'nom_sql' => 'type_article',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '5',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'article',
				'type_element' => 'article',
				'nom_sql' => 'tarif',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '6',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'article',
				'type_element' => 'article',
				'nom_sql' => 'prix_d_achat',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '7',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'article',
				'type_element' => 'article',
				'nom_sql' => 'stockable',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '8',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'article',
				'type_element' => 'article',
				'nom_sql' => 'description',
				'taille_avant' => '0',
				'taille_libelle' => '12',
				'taille_champ' => '12',
				'taille_apres' => '0',
				'ordre' => '9',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			],
	    ];