<?php
		return [
		'vue_js' => [
		'vuejs_data' => "",
		'vuejs_methods' => "",
		'surcharger_la_vue' => "",
		],
		'champs_libres' => [
			[
				'nom_formulaire' => "campagne_de_prospection",
				'type_element' => "campagne_de_prospection",
				'nom_sql' => "nom",
				'taille_avant' => "0",
				'taille_libelle' => "2",
				'taille_champ' => "4",
				'taille_apres' => "6",
				'ordre' => "1",
				'type_champ' => "0",
				'valeur_html' => "",
				'id_editeur' => "",
				'nom_vue' => "",
				'type_vue' => "",
				
			],
			
			[
				'nom_formulaire' => "campagne_de_prospection",
				'type_element' => "campagne_de_prospection",
				'nom_sql' => "date_de_debut",
				'taille_avant' => "0",
				'taille_libelle' => "2",
				'taille_champ' => "4",
				'taille_apres' => "0",
				'ordre' => "2",
				'type_champ' => "0",
				'valeur_html' => "",
				'id_editeur' => "",
				'nom_vue' => "",
				'type_vue' => "",
				
			],
			[
				'nom_formulaire' => "campagne_de_prospection",
				'type_element' => "campagne_de_prospection",
				'nom_sql' => "date_de_fin",
				'taille_avant' => "0",
				'taille_libelle' => "2",
				'taille_champ' => "4",
				'taille_apres' => "0",
				'ordre' => "3",
				'type_champ' => "0",
				'valeur_html' => "",
				'id_editeur' => "",
				'nom_vue' => "",
				'type_vue' => "",
				
			],
			
			[
				'nom_formulaire' => "campagne_de_prospection",
				'type_element' => "campagne_de_prospection",
				'nom_sql' => "budget",
				'taille_avant' => "0",
				'taille_libelle' => "2",
				'taille_champ' => "4",
				'taille_apres' => "0",
				'ordre' => "4",
				'type_champ' => "0",
				'valeur_html' => "",
				'id_editeur' => "",
				'nom_vue' => "",
				'type_vue' => "",
				
			],
			[
				'nom_formulaire' => "campagne_de_prospection",
				'type_element' => "campagne_de_prospection",
				'nom_sql' => "cout",
				'taille_avant' => "0",
				'taille_libelle' => "2",
				'taille_champ' => "4",
				'taille_apres' => "0",
				'ordre' => "5",
				'type_champ' => "0",
				'valeur_html' => "",
				'id_editeur' => "",
				'nom_vue' => "",
				'type_vue' => "",
				
			],
			[
				'nom_formulaire' => "campagne_de_prospection",
				'type_element' => "campagne_de_prospection",
				'nom_sql' => "objectif",
				'taille_avant' => "0",
				'taille_libelle' => "2",
				'taille_champ' => "4",
				'taille_apres' => "6",
				'ordre' => "6",
				'type_champ' => "0",
				'valeur_html' => "",
				'id_editeur' => "",
				'nom_vue' => "",
				'type_vue' => "",
				
			],
			[
				'nom_formulaire' => "campagne_de_prospection",
				'type_element' => "campagne_de_prospection",
				'nom_sql' => "details",
				'taille_avant' => "0",
				'taille_libelle' => "12",
				'taille_champ' => "12",
				'taille_apres' => "0",
				'ordre' => "8",
				'type_champ' => "0",
				'valeur_html' => "",
				'id_editeur' => "",
				'nom_vue' => "",
				'type_vue' => "",
				
			],
			
			[
				'nom_formulaire' => "campagne_de_prospection",
				'type_element' => "campagne_de_prospection",
				'nom_sql' => "utilisateurs",
				'taille_avant' => "0",
				'taille_libelle' => "12",
				'taille_champ' => "12",
				'taille_apres' => "0",
				'ordre' => "7",
				'type_champ' => "0",
				'valeur_html' => "",
				'id_editeur' => "",
				'nom_vue' => "",
				'type_vue' => "",
				
			],
			
			],
	];