<?php
		return [
		'vue_js' => [
            'vuejs_data' => "",
            'vuejs_methods' => "",
		],
		'champs_libres' => [
		[
            'nom_formulaire' => 'catalogue_tarif',
            'type_element' => 'catalogue_tarif',
            'nom_sql' => 'catalogue_groupement_id',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '6',
            'ordre' => '1',
        ],
        [
            'nom_formulaire' => 'catalogue_tarif',
            'type_element' => 'catalogue_tarif',
            'nom_sql' => 'nom',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '6',
            'ordre' => '2',
        ],
        [
            'nom_formulaire' => 'catalogue_tarif',
            'type_element' => 'catalogue_tarif',
            'nom_sql' => 'date_debut',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '0',
            'ordre' => '3',
        ],
        [
            'nom_formulaire' => 'catalogue_tarif',
            'type_element' => 'catalogue_tarif',
            'nom_sql' => 'date_fin',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '0',
            'ordre' => '4',
        ],
    ],
    'valeurs_par_defaut' => [],
];