<?php
return [
    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
        'surcharger_la_vue' => "",
    ],
    'champs_libres' => [
        [
            'type_element' => 'categorie_eco_contribution',
            'nom_sql' => 'famille_id',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "1",
        ],
        [
            'type_element' => 'categorie_eco_contribution',
            'nom_sql' => 'nom',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "2",
        ],
        [
            'type_element' => 'categorie_eco_contribution',
            'nom_sql' => 'code',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "3",
        ],
        [
            'type_element' => 'categorie_eco_contribution',
            'nom_sql' => 'unite',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "4",
        ],
        [
            'type_element' => 'categorie_eco_contribution',
            'nom_sql' => 'exemple',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "10",
            'taille_apres' => "0",
            'ordre' => "5",
        ],
    ],
];
