<?php return [

		        'vue_js' => [
		            'vuejs_data' => "",
		            'vuejs_methods' => "",
		            'surcharger_la_vue' => "1",
                ],
                'champs_libres' => [
		[
			'nom_formulaire' => 'client',
				'type_element' => 'client',
				'nom_sql' => 'raison_sociale',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '0',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'client',
				'type_element' => 'client',
				'nom_sql' => 'type',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '1',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'client',
				'type_element' => 'client',
				'nom_sql' => 'statut',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '2',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'client',
				'type_element' => 'client',
				'nom_sql' => 'responsable_commercial',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '3',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'client',
				'type_element' => 'client',
				'nom_sql' => 'site_web',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '4',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'client',
				'type_element' => 'client',
				'nom_sql' => 'telephone',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '5',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			],
	    ];