<?php return [

		        'vue_js' => [
		            'vuejs_data' => "",
		            'vuejs_methods' => "",
		            'surcharger_la_vue' => "",
                ],
                'champs_libres' => [
		[
			'nom_formulaire' => 'commande_vente',
				'type_element' => 'commande_vente',
				'nom_sql' => 'objet',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '10',
				'taille_apres' => '0',
				'ordre' => '0',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'commande_vente',
				'type_element' => 'commande_vente',
				'nom_sql' => 'date',
				'taille_avant' => '0',
				'taille_libelle' => '6',
				'taille_champ' => '6',
				'taille_apres' => '0',
				'ordre' => '1',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'commande_vente',
				'type_element' => 'commande_vente',
				'nom_sql' => 'responsable_commercial_id',
				'taille_avant' => '0',
				'taille_libelle' => '6',
				'taille_champ' => '6',
				'taille_apres' => '0',
				'ordre' => '2',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'commande_vente',
				'type_element' => 'commande_vente',
				'nom_sql' => 'date_livraison',
				'taille_avant' => '0',
				'taille_libelle' => '6',
				'taille_champ' => '6',
				'taille_apres' => '0',
				'ordre' => '3',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
				'nom_formulaire' => 'commande_vente',
				'type_element' => 'commande_vente',
				'nom_sql' => 'nature_article_modele',
				'taille_avant' => '0',
				'taille_libelle' => '6',
				'taille_champ' => '6',
				'taille_apres' => '0',
				'ordre' => '4',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			],
	    ];