<?php
return [
    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
    ],
    'champs_libres' => [
        [
            'nom_formulaire' => 'compte_email',
            'type_element' => 'compte_email',
            'nom_sql' => 'Intégration bloc html 1',
            'taille_avant' => '0',
            'taille_libelle' => '0',
            'taille_champ' => '12',
            'taille_apres' => '0',
            'ordre' => '1',
            'type_champ' => '1',
            'valeur_html' => '<div class="row"><div class="col-sm-12 css_form_ligne_titre">{{ this.$root.traduction(\'formulaire.divers.informations_generales\')}}</div></div>',
        ],
        [
            'nom_formulaire' => "compte_email",
            'type_element' => "compte_email",
            'nom_sql' => "type_de_compte",
            'taille_avant' => "0",
            'taille_libelle' => "4",
            'taille_champ' => "8",
            'taille_apres' => "0",
            'ordre' => "2",

        ],
        [
            'nom_formulaire' => "compte_email",
            'type_element' => "compte_email",
            'nom_sql' => "adresse_email",
            'taille_avant' => "0",
            'taille_libelle' => "4",
            'taille_champ' => "8",
            'taille_apres' => "0",
            'condition_affichage_v_if' => 'compte_email.type_de_compte == 0',
            'condition_obligatoire' => 'compte_email.type_de_compte == 0',
            'ordre' => "2",

        ],
        [
            'nom_formulaire' => "compte_email",
            'type_element' => "compte_email",
            'nom_sql' => "nom_expediteur",
            'taille_avant' => "0",
            'taille_libelle' => "4",
            'taille_champ' => "8",
            'taille_apres' => "0",
            'condition_affichage_v_if' => 'compte_email.type_de_compte == 0',
            'ordre' => "3",

        ],
        [
            'nom_formulaire' => "compte_email",
            'type_element' => "compte_email",
            'nom_sql' => "alias",
            'taille_avant' => "0",
            'taille_libelle' => "4",
            'taille_champ' => "8",
            'taille_apres' => "0",
            'condition_affichage_v_if' => 'compte_email.type_de_compte == 0',
            'ordre' => "4",

        ],
        [
            'nom_formulaire' => "compte_email",
            'type_element' => "compte_email",
            'nom_sql' => "utilisateur_id",
            'taille_avant' => "0",
            'taille_libelle' => "4",
            'taille_champ' => "8",
            'taille_apres' => "0",
            'ordre' => "5",

        ],
        [
            'nom_formulaire' => "compte_email",
            'type_element' => "compte_email",
            'nom_sql' => "mail_public",
            'taille_avant' => "0",
            'taille_libelle' => "4",
            'taille_champ' => "8",
            'taille_apres' => "0",
            'ordre' => "6",

        ],
        [
            'type_element' => "compte_email",
            'nom_sql' => "",
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => "7",
            'type_champ' => 2,
            'nom_vue' => "mdp_smtp",
            'condition_affichage_v_if' => 'compte_email.type_de_compte == 0',
            'type_vue' => "standard",
        ],
        [
            'nom_formulaire' => "compte_email",
            'type_element' => "compte_email",
            'nom_sql' => "image_signature",
            'taille_avant' => "0",
            'taille_libelle' => "4",
            'taille_champ' => "8",
            'taille_apres' => "0",
            'ordre' => "8",

        ],
        [
            'nom_formulaire' => "compte_email",
            'type_element' => "compte_email",
            'nom_sql' => "configuration_email",
            'taille_avant' => "0",
            'taille_libelle' => "4",
            'taille_champ' => "8",
            'taille_apres' => "0",
            'condition_affichage_v_if' => 'compte_email.type_de_compte == 0',
            'ordre' => "9",

        ],
        [
            'type_element' => "compte_email",
            'nom_sql' => "",
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => "10",
            'type_champ' => 2,
            'nom_vue' => "notes_importantes",
            'type_vue' => "standard",
        ],
    ],
];
