<?php
    return [
		'vue_js' => [
            'vuejs_data' => "",
            'vuejs_methods' => "",
		],
		'champs_libres' => [
		    [
                'nom_formulaire' => 'condition_commerciale',
                'type_element' => 'condition_commerciale',
                'nom_sql' => 'famille_id',
                'taille_avant' => '0',
                'taille_libelle' => '2',
                'taille_champ' => '4',
                'taille_apres' => '0',
                'ordre' => '0',
                'condition_affichage_v_if' => '!condition_commerciale.article_id && !condition_commerciale.article_fournisseur_id',
            ],
            [
                'nom_formulaire' => 'condition_commerciale',
                'type_element' => 'condition_commerciale',
                'nom_sql' => 'article_id',
                'taille_avant' => '0',
                'taille_libelle' => '2',
                'taille_champ' => '4',
                'taille_apres' => '0',
                'ordre' => '2',
                'condition_affichage_v_if' => '!condition_commerciale.famille_id && !condition_commerciale.article_fournisseur_id',
            ],
			[
                'nom_formulaire' => 'condition_commerciale',
                'type_element' => 'condition_commerciale',
                'nom_sql' => 'article_fournisseur_id',
                'taille_avant' => '0',
                'taille_libelle' => '2',
                'taille_champ' => '4',
                'taille_apres' => '0',
                'ordre' => '3',
                'condition_affichage_v_if' => '!condition_commerciale.famille_id && !condition_commerciale.article_id && !condition_commerciale.client_id',
            ],
            [
                'nom_formulaire' => 'condition_commerciale',
                'type_element' => 'condition_commerciale',
                'nom_sql' => 'catalogue_tarif_id',
                'taille_avant' => '0',
                'taille_libelle' => '2',
                'taille_champ' => '4',
                'taille_apres' => '0',
                'ordre' => '4',
                'condition_affichage_v_if' => '!condition_commerciale.client_id',
            ],
			[
				'nom_formulaire' => 'condition_commerciale',
				'type_element' => 'condition_commerciale',
				'nom_sql' => 'client_id',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '5',
				'condition_affichage_v_if' => '!(condition_commerciale.catalogue_tarif_id) && !(condition_commerciale.article_fournisseur_id)',
			],
			[
				'nom_formulaire' => 'condition_commerciale',
				'type_element' => 'condition_commerciale',
				'nom_sql' => 'conditionnement',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '6',
				'condition_affichage_v_if' => 'condition_commerciale.article_id',
			],
			[
				'nom_formulaire' => 'condition_commerciale',
				'type_element' => 'condition_commerciale',
				'nom_sql' => 'palier_quantite',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '7',
			],
			[
				'nom_formulaire' => 'condition_commerciale',
				'type_element' => 'condition_commerciale',
				'nom_sql' => 'tarif',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '8',
				'condition_affichage_v_if' => '!condition_commerciale.article_fournisseur_id',
			],
			[
				'nom_formulaire' => 'condition_commerciale',
				'type_element' => 'condition_commerciale',
				'nom_sql' => 'remise',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '9',
				'condition_affichage_v_if' => '!condition_commerciale.article_fournisseur_id',
			],
			[
				'nom_formulaire' => 'condition_commerciale',
				'type_element' => 'condition_commerciale',
				'nom_sql' => 'prix_achat',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '10',
			],
        ],
		'valeurs_par_defaut' => [],
    ];