<?php
return [
    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
        'surcharger_la_vue' => "",
    ],
    'champs_libres' => [
        [
            'nom_formulaire' => "docusign_enveloppe",
            'type_element' => 'docusign_enveloppe',
            'nom_sql' => 'type_element',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "1",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
            'condition_lecture_seule' => 'docusign_enveloppe.id > 0',
        ],
        [
            'nom_formulaire' => "docusign_enveloppe",
            'type_element' => 'docusign_enveloppe',
            'nom_sql' => 'element_id',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "2",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
            'condition_lecture_seule' => 'docusign_enveloppe.id > 0',
        ],
        [
            'nom_formulaire' => 'docusign_enveloppe',
            'type_element' => 'docusign_enveloppe',
            'nom_sql' => '',
            'taille_avant' => '',
            'taille_libelle' => '',
            'taille_champ' => '',
            'taille_apres' => '',
            'ordre' => '3',
            'type_champ' => '3',
            'nom_sous_formulaire' => 'docusign_enveloppe_sous_formulaire_docusign_signataire',
            'nom_affichage_sous_formulaire' => 'Signataire',
            'condition_affichage_v_if' => 'docusign_enveloppe.element_id > 0',
        ],
        [
            'nom_formulaire' => 'docusign_enveloppe',
            'type_element' => 'docusign_enveloppe',
            'nom_sql' => '',
            'taille_avant' => '',
            'taille_libelle' => '',
            'taille_champ' => '',
            'taille_apres' => '',
            'ordre' => '4',
            'type_champ' => '3',
            'nom_sous_formulaire' => 'docusign_enveloppe_sous_formulaire_docusign_document',
            'nom_affichage_sous_formulaire' => 'Document',
            'condition_affichage_v_if' => 'docusign_enveloppe.element_id > 0',
        ]
    ],
];