<?php
return [
    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
        'surcharger_la_vue' => "",
    ],
    'champs_libres' => [
        [
            'type_element' => 'echeance',
            'nom_sql' => 'type_element',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "1",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
        ],
        [
            'type_element' => 'echeance',
            'nom_sql' => 'element_id',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "2",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
        ],
        [
            'type_element' => 'echeance',
            'nom_sql' => 'titre',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "3",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
        ],
        [
            'type_element' => 'echeance',
            'nom_sql' => 'date',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "4",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
        ],
        [
            'type_element' => 'echeance',
            'nom_sql' => '',
            'taille_avant' => '0',
            'taille_libelle' => '0',
            'taille_champ' => '12',
            'taille_apres' => '0',
            'ordre' => '5',
            'type_champ' => '2',
            'id_editeur' => '0',
            'nom_vue' => 'creation_multiple',
            'type_vue' => 'standard',
            'condition_affichage_v_if' => '!(echeance.id > 0)'
        ],
        [
            'type_element' => 'echeance',
            'nom_sql' => 'pourcentage',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "6",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
            'condition_affichage_v_if' => 'creation_multiple != 1'
        ],
        [
            'type_element' => 'echeance',
            'nom_sql' => 'montant',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "7",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
            'condition_affichage_v_if' => 'creation_multiple != 1 && echeance.pourcentage != 1'
        ],
        [
            'type_element' => 'echeance',
            'nom_sql' => 'montant_pourcentage',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "8",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
            'condition_affichage_v_if' => 'creation_multiple != 1 && echeance.pourcentage == 1'
        ],
    ],
];
