<?php return [

	'vue_js' => [
		'vuejs_data' => "",
		'vuejs_methods' => "",
		'surcharger_la_vue' => "",
	],
	'champs_libres' => [
		[
			'nom_formulaire' => 'facturation_electronique_achat',
			'type_element' => 'facturation_electronique_achat',
			'nom_sql' => 'reference_document',
			'taille_avant' => '0',
			'taille_libelle' => '4',
			'taille_champ' => '8',
			'taille_apres' => '0',
			'ordre' => '1',
		],
		[
			'nom_formulaire' => 'facturation_electronique_achat',
			'type_element' => 'facturation_electronique_achat',
			'nom_sql' => 'date_document',
			'taille_avant' => '0',
			'taille_libelle' => '4',
			'taille_champ' => '8',
			'taille_apres' => '0',
			'ordre' => '2',
		],
		[
			'nom_formulaire' => 'facturation_electronique_achat',
			'type_element' => 'facturation_electronique_achat',
			'nom_sql' => 'type_code_facturx',
			'taille_avant' => '0',
			'taille_libelle' => '4',
			'taille_champ' => '8',
			'taille_apres' => '0',
			'ordre' => '3',
		],
		[
			'nom_formulaire' => 'facturation_electronique_achat',
			'type_element' => 'facturation_electronique_achat',
			'nom_sql' => 'statut_facturation_electronique',
			'taille_avant' => '0',
			'taille_libelle' => '4',
			'taille_champ' => '8',
			'taille_apres' => '0',
			'ordre' => '4',
		],
		[
			'nom_formulaire' => 'facturation_electronique_achat',
			'type_element' => 'facturation_electronique_achat',
			'nom_sql' => 'siren_emetteur',
			'taille_avant' => '0',
			'taille_libelle' => '4',
			'taille_champ' => '8',
			'taille_apres' => '0',
			'ordre' => '5',
		],
		[
			'nom_formulaire' => 'facturation_electronique_achat',
			'type_element' => 'facturation_electronique_achat',
			'nom_sql' => 'nom_emetteur',
			'taille_avant' => '0',
			'taille_libelle' => '4',
			'taille_champ' => '8',
			'taille_apres' => '0',
			'ordre' => '6',
		],
		[
			'nom_formulaire' => 'facturation_electronique_achat',
			'type_element' => 'facturation_electronique_achat',
			'nom_sql' => 'entite_id',
			'taille_avant' => '0',
			'taille_libelle' => '4',
			'taille_champ' => '8',
			'taille_apres' => '0',
			'ordre' => '7',
		],
		[
			'nom_formulaire' => 'facturation_electronique_achat',
			'type_element' => 'facturation_electronique_achat',
			'nom_sql' => 'siren_destinataire',
			'taille_avant' => '0',
			'taille_libelle' => '4',
			'taille_champ' => '8',
			'taille_apres' => '0',
			'ordre' => '8',
		],
		[
			'nom_formulaire' => 'facturation_electronique_achat',
			'type_element' => 'facturation_electronique_achat',
			'nom_sql' => 'montant_ht',
			'taille_avant' => '0',
			'taille_libelle' => '4',
			'taille_champ' => '8',
			'taille_apres' => '0',
			'ordre' => '9',
		],
		[
			'nom_formulaire' => 'facturation_electronique_achat',
			'type_element' => 'facturation_electronique_achat',
			'nom_sql' => 'montant_tva',
			'taille_avant' => '0',
			'taille_libelle' => '4',
			'taille_champ' => '8',
			'taille_apres' => '0',
			'ordre' => '10',
		],
		[
			'nom_formulaire' => 'facturation_electronique_achat',
			'type_element' => 'facturation_electronique_achat',
			'nom_sql' => 'montant_ttc',
			'taille_avant' => '0',
			'taille_libelle' => '4',
			'taille_champ' => '8',
			'taille_apres' => '0',
			'ordre' => '11',
		],
		[
			'nom_formulaire' => 'facturation_electronique_achat',
			'type_element' => 'facturation_electronique_achat',
			'nom_sql' => 'pdf',
			'taille_avant' => '0',
			'taille_libelle' => '4',
			'taille_champ' => '8',
			'taille_apres' => '0',
			'ordre' => '12',
		],
		[
			'nom_formulaire' => 'facturation_electronique_achat',
			'type_element' => 'facturation_electronique_achat',
			'nom_sql' => 'tracking_id',
			'taille_avant' => '0',
			'taille_libelle' => '4',
			'taille_champ' => '8',
			'taille_apres' => '0',
			'ordre' => '13',
		],
		[
			'nom_formulaire' => 'facturation_electronique_achat',
			'type_element' => 'facturation_electronique_achat',
			'nom_sql' => 'flow_type',
			'taille_avant' => '0',
			'taille_libelle' => '4',
			'taille_champ' => '8',
			'taille_apres' => '0',
			'ordre' => '14',
		],
		[
			'nom_formulaire' => 'facturation_electronique_achat',
			'type_element' => 'facturation_electronique_achat',
			'nom_sql' => 'flow_id',
			'taille_avant' => '0',
			'taille_libelle' => '4',
			'taille_champ' => '8',
			'taille_apres' => '0',
			'ordre' => '15',
		],
	],
];
