<?php return [

    'type_element' => 'facture_achat',
    'titre_formulaire' => traduction('document.blocs.fournisseur.titre'),
    'champs_libres' => [
        [
            'nom_formulaire' => 'facture_achat_fournisseur',
            'type_element' => 'facture_achat',
            'nom_sql' => 'fournisseur_id',
            'taille_avant' => '0',
            'taille_libelle' => '12',
            'taille_champ' => '12',
            'taille_apres' => '',
            'ordre' => '1',
        ],
        [
            'nom_formulaire' => 'facture_achat_fournisseur',
            'type_element' => 'facture_achat',
            'nom_sql' => 'projet_id',
            'taille_avant' => '0',
            'taille_libelle' => '12',
            'taille_champ' => '12',
            'taille_apres' => '',
            'ordre' => '2',
        ],
        [
            'nom_formulaire' => 'facture_achat_fournisseur',
            'type_element' => 'facture_achat',
            'nom_sql' => 'a_livrer_chez_client',
            'taille_avant' => '0',
            'taille_libelle' => '12',
            'taille_champ' => '12',
            'taille_apres' => '',
            'ordre' => '3',
        ],
        [
            'nom_formulaire' => 'facture_achat_fournisseur',
            'type_element' => 'facture_achat',
            'nom_sql' => 'client_id',
            'taille_avant' => '0',
            'taille_libelle' => '12',
            'taille_champ' => '12',
            'taille_apres' => '',
            'ordre' => '4',
            'condition_affichage_v_if' => 'document.a_livrer_chez_client',
        ],
        [
            'nom_formulaire' => 'facture_achat_fournisseur',
            'type_element' => 'facture_achat',
            'nom_sql' => 'adresse_de_livraison',
            'taille_avant' => '0',
            'taille_libelle' => '12',
            'taille_champ' => '12',
            'taille_apres' => '',
            'ordre' => '5',
            'condition_obligatoire' => "(document.a_livrer_chez_client == false || document.a_livrer_chez_client == undefined) && (document.adresse_de_livraison_texte == '' || document.adresse_de_livraison_texte == null)",
            'condition_affichage_v_if' => 'document.a_livrer_chez_client == false || document.a_livrer_chez_client == undefined',
        ],
        [
            'nom_formulaire' => 'facture_achat_fournisseur',
            'type_element' => 'facture_achat',
            'nom_sql' => 'adresse_de_livraison_client',
            'taille_avant' => '0',
            'taille_libelle' => '12',
            'taille_champ' => '12',
            'taille_apres' => '',
            'ordre' => '6',
            'condition_obligatoire' => "document.a_livrer_chez_client && (document.adresse_de_livraison_texte == '' || document.adresse_de_livraison_texte == null)",
            'condition_affichage_v_if' => 'document.a_livrer_chez_client',
        ],
        [
            'nom_formulaire' => 'facture_achat_fournisseur',
            'type_element' => 'facture_achat',
            'nom_sql' => 'adresse_de_livraison_texte',
            'taille_avant' => '0',
            'taille_libelle' => '12',
            'taille_champ' => '12',
            'taille_apres' => '',
            'ordre' => '7',
        ],
        [
            'nom_formulaire' => 'facture_achat_fournisseur',
            'type_element' => 'facture_achat',
            'nom_sql' => 'adresse_de_facturation',
            'taille_avant' => '0',
            'taille_libelle' => '12',
            'taille_champ' => '12',
            'taille_apres' => '0',
            'ordre' => '8',
            'condition_obligatoire' => "document.adresse_de_facturation_texte == '' || document.adresse_de_facturation_texte == null",
        ],
        [
            'nom_formulaire' => 'facture_achat_fournisseur',
            'type_element' => 'facture_achat',
            'nom_sql' => 'adresse_de_facturation_texte',
            'taille_avant' => '0',
            'taille_libelle' => '12',
            'taille_champ' => '12',
            'taille_apres' => '0',
            'ordre' => '9',
        ],
        [
            'nom_formulaire' => "facture_achat_fournisseur",
            'type_element' => "facture_achat",
            'nom_sql' => "",
            'ordre' => 10,
            'taille_avant' => 0,
            'taille_libelle' => 0,
            'taille_champ' => 12,
            'taille_apres' => 0,
            'type_champ' => 2,
            'nom_vue' => "watch_vuejs_adresses",
            'type_vue' => "document_achat_standard",
        ],
    ]
];