<?php return [

		        'vue_js' => [
		            'vuejs_data' => "",
		            'vuejs_methods' => "",
		            'surcharger_la_vue' => "",
                ],
                'champs_libres' => [
		[
			'nom_formulaire' => 'facturation_electronique_cycle_de_vie',
				'type_element' => 'facturation_electronique_cycle_de_vie',
				'nom_sql' => 'facturation_electronique_achat_id',
				'taille_avant' => '0',
				'taille_libelle' => '4',
				'taille_champ' => '8',
				'taille_apres' => '0',
				'ordre' => '1',
				'condition_affichage_v_if' => '!facturation_electronique_cycle_de_vie.facture_vente_id && !facturation_electronique_cycle_de_vie.avoir_vente_id',
				'condition_obligatoire' => '!facturation_electronique_cycle_de_vie.facture_vente_id && !facturation_electronique_cycle_de_vie.avoir_vente_id',
				'condition_lecture_seule' => 'facturation_electronique_cycle_de_vie.id > 0',
			],
			[
				'nom_formulaire' => 'facturation_electronique_cycle_de_vie',
				'type_element' => 'facturation_electronique_cycle_de_vie',
				'nom_sql' => 'facture_vente_id',
				'taille_avant' => '0',
				'taille_libelle' => '4',
				'taille_champ' => '8',
				'taille_apres' => '0',
				'ordre' => '2',
				'condition_affichage_v_if' => '!facturation_electronique_cycle_de_vie.facturation_electronique_achat_id && !facturation_electronique_cycle_de_vie.avoir_vente_id',
				'condition_obligatoire' => '!facturation_electronique_cycle_de_vie.facturation_electronique_achat_id && !facturation_electronique_cycle_de_vie.avoir_vente_id',
				'condition_lecture_seule' => 'facturation_electronique_cycle_de_vie.id > 0',
			],
			[
				'nom_formulaire' => 'facturation_electronique_cycle_de_vie',
				'type_element' => 'facturation_electronique_cycle_de_vie',
				'nom_sql' => 'avoir_vente_id',
				'taille_avant' => '0',
				'taille_libelle' => '4',
				'taille_champ' => '8',
				'taille_apres' => '0',
				'ordre' => '3',
				'condition_affichage_v_if' => '!facturation_electronique_cycle_de_vie.facturation_electronique_achat_id && !facturation_electronique_cycle_de_vie.facture_vente_id',
				'condition_obligatoire' => '!facturation_electronique_cycle_de_vie.facturation_electronique_achat_id && !facturation_electronique_cycle_de_vie.facture_vente_id',
				'condition_lecture_seule' => 'facturation_electronique_cycle_de_vie.id > 0',
			],
			[
				'nom_formulaire' => 'facturation_electronique_cycle_de_vie',
				'type_element' => 'facturation_electronique_cycle_de_vie',
				'nom_sql' => '',
				'taille_avant' => '0',
				'taille_libelle' => '0',
				'taille_champ' => '12',
				'taille_apres' => '0',
				'ordre' => '4',
				'type_champ' => '2',
				'nom_vue' => 'statuts_postables',
				'type_vue' => 'standard',
			],
			[
				'nom_formulaire' => 'facturation_electronique_cycle_de_vie',
				'type_element' => 'facturation_electronique_cycle_de_vie',
				'nom_sql' => 'statut_achat',
				'taille_avant' => '0',
				'taille_libelle' => '0',
				'taille_champ' => '0',
				'taille_apres' => '0',
				'ordre' => '5',
				'condition_affichage_v_if' => 'false',
				'condition_obligatoire' => 'facturation_electronique_cycle_de_vie.facturation_electronique_achat_id',
			],
			[
				'nom_formulaire' => 'facturation_electronique_cycle_de_vie',
				'type_element' => 'facturation_electronique_cycle_de_vie',
				'nom_sql' => 'statut_vente',
				'taille_avant' => '0',
				'taille_libelle' => '0',
				'taille_champ' => '0',
				'taille_apres' => '0',
				'ordre' => '5',
				'condition_affichage_v_if' => 'false',
				'condition_obligatoire' => 'facturation_electronique_cycle_de_vie.facture_vente_id || facturation_electronique_cycle_de_vie.avoir_vente_id',
			],
			[
				'nom_formulaire' => 'facturation_electronique_cycle_de_vie',
				'type_element' => 'facturation_electronique_cycle_de_vie',
				'nom_sql' => 'motif_code',
				'taille_avant' => '0',
				'taille_libelle' => '0',
				'taille_champ' => '0',
				'taille_apres' => '0',
				'ordre' => '6',
				'condition_affichage_v_if' => 'false',
				'condition_obligatoire' => "[206,207,208,210,213,501].includes(Number(facturation_electronique_cycle_de_vie.statut_achat)) || [206,207,208,210,213,501].includes(Number(facturation_electronique_cycle_de_vie.statut_vente))",
			],
			[
				'nom_formulaire' => 'facturation_electronique_cycle_de_vie',
				'type_element' => 'facturation_electronique_cycle_de_vie',
				'nom_sql' => 'motif',
				'taille_avant' => '0',
				'taille_libelle' => '4',
				'taille_champ' => '8',
				'taille_apres' => '0',
				'ordre' => '7',
			],
			[
				'nom_formulaire' => 'facturation_electronique_cycle_de_vie',
				'type_element' => 'facturation_electronique_cycle_de_vie',
				'nom_sql' => 'flow_id',
				'taille_avant' => '0',
				'taille_libelle' => '4',
				'taille_champ' => '8',
				'taille_apres' => '0',
				'ordre' => '8',
				'condition_affichage_v_if' => 'facturation_electronique_cycle_de_vie.flow_id',
			],
			],
	    ];
