<?php return [
    'type_formulaire' => 'fiche',
		        'vue_js' => [
		            'vuejs_data' => "",
		            'vuejs_methods' => "",
		            'surcharger_la_vue' => "",
                ],
                'champs_libres' => [
		[
			'nom_formulaire' => 'fiche_ticket_client',
				'type_element' => 'ticket_client',
				'nom_sql' => 'numero',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '1',
				'condition_lecture_seule' => '1',
				
			],
			[
			'nom_formulaire' => 'fiche_ticket_client',
				'type_element' => 'ticket_client',
				'nom_sql' => 'date',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '0',
				'condition_lecture_seule' => '1',
				
			],
			[
			'nom_formulaire' => 'fiche_ticket_client',
				'type_element' => 'ticket_client',
				'nom_sql' => 'titre',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '4',
				
			],
			[
			'nom_formulaire' => 'fiche_ticket_client',
				'type_element' => 'ticket_client',
				'nom_sql' => 'type_probleme',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '5',
				
			],
			[
			'nom_formulaire' => 'fiche_ticket_client',
				'type_element' => 'ticket_client',
				'nom_sql' => 'type_solution',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '7',
				
			],
			[
			'nom_formulaire' => 'fiche_ticket_client',
				'type_element' => 'ticket_client',
				'nom_sql' => 'source',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '11',
				
			],
			[
			'nom_formulaire' => 'fiche_ticket_client',
				'type_element' => 'ticket_client',
				'nom_sql' => 'statut',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '10',
				
			],
			[
			'nom_formulaire' => 'fiche_ticket_client',
				'type_element' => 'ticket_client',
				'nom_sql' => 'priorite',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '9',
				
			],
			[
			'nom_formulaire' => 'fiche_ticket_client',
				'type_element' => 'ticket_client',
				'nom_sql' => 'utilisateur_id',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '12',
				
			],
			[
			'nom_formulaire' => 'fiche_ticket_client',
				'type_element' => 'ticket_client',
				'nom_sql' => 'description',
				'taille_avant' => '0',
				'taille_libelle' => '12',
				'taille_champ' => '12',
				'taille_apres' => '0',
				'ordre' => '6',
				
			],
			[
			'nom_formulaire' => 'fiche_ticket_client',
				'type_element' => 'ticket_client',
				'nom_sql' => 'details_solution',
				'taille_avant' => '0',
				'taille_libelle' => '12',
				'taille_champ' => '12',
				'taille_apres' => '0',
				'ordre' => '8',
				
			],
			[
			'nom_formulaire' => 'fiche_ticket_client',
				'type_element' => 'ticket_client',
				'nom_sql' => 'client_id',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '2',
				
			],
			[
			'nom_formulaire' => 'fiche_ticket_client',
				'type_element' => 'ticket_client',
				'nom_sql' => 'contact',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '3',
				
			],
			[
			'nom_formulaire' => 'fiche_ticket_client',
				'type_element' => 'ticket_client',
				'nom_sql' => 'date_cloture',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '13',
				
			],
			],
	    ];