<?php
return [
    'type_element' => 'paiement',
    'titre_formulaire' => 'Formulaire pour les documents décaissement',
    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
        'surcharger_la_vue' => "",
    ],
    'champs_libres' => [
        [
            'nom_formulaire' => "formulaire_documents_paiement_decaissement",
            'type_element' => 'paiement',
            'nom_sql' => 'type_element',
            'ordre' => 1,
            'taille_avant' => 0,
            'taille_libelle' => 2,
            'taille_champ' => 4,
            'taille_apres' => 0,
        ],
        [
            'nom_formulaire' => "formulaire_documents_paiement_decaissement",
            'type_element' => 'paiement',
            'nom_sql' => 'id_document',
            'ordre' => 2,
            'taille_avant' => 0,
            'taille_libelle' => 2,
            'taille_champ' => 4,
            'taille_apres' => 0,
        ],
        [
            'nom_formulaire' => "formulaire_documents_paiement_decaissement",
            'type_element' => 'paiement',
            'nom_sql' => 'date',
            'ordre' => 3,
            'taille_avant' => 0,
            'taille_libelle' => 2,
            'taille_champ' => 4,
            'taille_apres' => 6,
        ],
        [
            'nom_formulaire' => "formulaire_documents_paiement_decaissement",
            'type_element' => 'paiement',
            'nom_sql' => 'montant_saisi',
            'ordre' => 4,
            'taille_avant' => 0,
            'taille_libelle' => 2,
            'taille_champ' => 4,
            'taille_apres' => 0,
        ],
        [
            'nom_formulaire' => "formulaire_documents_paiement_decaissement",
            'type_element' => 'paiement',
            'nom_sql' => 'type',
            'ordre' => 5,
            'taille_avant' => 0,
            'taille_libelle' => 2,
            'taille_champ' => 4,
            'taille_apres' => 0,
        ],
        [
            'nom_formulaire' => "formulaire_documents_paiement_decaissement",
            'type_element' => 'paiement',
            'nom_sql' => 'mode_paiement_id',
            'ordre' => 6,
            'taille_avant' => 0,
            'taille_libelle' => 2,
            'taille_champ' => 4,
            'taille_apres' => 0,
        ],
        [
            'nom_formulaire' => "formulaire_documents_paiement_decaissement",
            'type_element' => 'paiement',
            'nom_sql' => 'compte_bancaire_id',
            'ordre' => 7,
            'taille_avant' => 0,
            'taille_libelle' => 2,
            'taille_champ' => 4,
            'taille_apres' => 0,
        ],
        [
            'nom_formulaire' => "formulaire_documents_paiement_decaissement",
            'type_element' => 'paiement',
            'nom_sql' => 'fournisseur_id',
            'ordre' => 8,
            'taille_avant' => 0,
            'taille_libelle' => 2,
            'taille_champ' => 10,
            'taille_apres' => 0,
            'condition_affichage_v_if' => "paiement.client_id == undefined || paiement.client_id == '' || paiement.client_id == 0 || paiement.client_id == null",
        ],
        [
            'nom_formulaire' => "formulaire_documents_paiement_decaissement",
            'type_element' => 'paiement',
            'nom_sql' => 'client_id',
            'ordre' => 9,
            'taille_avant' => 0,
            'taille_libelle' => 2,
            'taille_champ' => 10,
            'taille_apres' => 0,
            'condition_affichage_v_if' => "paiement.fournisseur_id == undefined || paiement.fournisseur_id == '' || paiement.fournisseur_id == 0 || paiement.fournisseur_id == null",
        ],
        [
            'nom_formulaire' => "formulaire_documents_paiement_decaissement",
            'type_element' => "paiement",
            'nom_sql' => '',
            'taille_champ' => 12,
            'ordre' => 10,
            'type_champ' => 2,
            'nom_vue' => "rattache_paiement_existant",
            'type_vue' => "standard",
        ],
    ],
    'valeurs_par_defaut' => [
		[
            'nom_formulaire' => 'formulaire_documents_paiement_decaissement',
            'nom_sql' => 'type',
            'valeur' => 1,
        ],
    ]
];
