<?php
return [
    'type_element' => 'tache',
    'titre_formulaire' => 'Formulaire ajout en masse de tâches',
    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
        'surcharger_la_vue' => "1",
    ],
    'champs_libres' => [
        [
            'type_element' => "tache",
            'nom_sql' => "titre",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "6",
            'taille_apres' => "0",
            'ordre' => "1",
        ],
        [
            'type_element' => "tache",
            'nom_sql' => "affectation",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "6",
            'taille_apres' => "0",
            'ordre' => "1",
        ],
        [
            'type_element' => "tache",
            'nom_sql' => "type_tache_todo",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "6",
            'taille_apres' => "0",
            'ordre' => "2",
        ],
        [
            'type_element' => "tache",
            'nom_sql' => "date_de_debut",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "6",
            'taille_apres' => "0",
            'ordre' => "3",
        ],
        [
            'type_element' => "tache",
            'nom_sql' => "urgent",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "6",
            'taille_apres' => "0",
            'ordre' => "6",
        ],
        [
            'type_element' => "tache",
            'nom_sql' => "commentaire",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "6",
            'taille_apres' => "0",
            'ordre' => "8",
        ],
    ],
];