<?php return [
	'type_element' => 'tache',
    'titre_formulaire' => 'Formulaire tache rdv',
	'vue_js' => [
		'vuejs_data' => "",
		'vuejs_methods' => "",
		'surcharger_la_vue' => "1",
	],
	'champs_libres' => [
		[
			'nom_formulaire' => 'formulaire_2_tache',
				'type_element' => 'tache',
				'nom_sql' => 'titre',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '6',
				'taille_apres' => '4',
				'ordre' => '0',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'formulaire_2_tache',
				'type_element' => 'tache',
				'nom_sql' => 'type_tache_rdv',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '6',
				'taille_apres' => '4',
				'ordre' => '1',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'formulaire_2_tache',
				'type_element' => 'tache',
				'nom_sql' => '',
				'taille_avant' => '0',
				'taille_libelle' => '0',
				'taille_champ' => '12',
				'taille_apres' => '0',
				'ordre' => '2',
				'type_champ' => '2',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '0',
				'nom_vue' => 'dates',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			    'nom_formulaire' => 'formulaire_2_tache',
				'type_element' => 'tache',
				'nom_sql' => 'affectation',
				'taille_avant' => '0',
				'taille_libelle' => '0',
				'taille_champ' => '12',
				'taille_apres' => '0',
				'ordre' => '3',
			],
            [
                'nom_formulaire' => 'formulaire_2_tache',
				'type_element' => 'tache',
				'nom_sql' => '',
				'taille_avant' => '0',
				'taille_libelle' => '0',
				'taille_champ' => '12',
				'taille_apres' => '0',
				'ordre' => '3',
				'type_champ' => '2',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '0',
				'nom_vue' => 'participants',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',

			],
			[
			'nom_formulaire' => 'formulaire_2_tache',
				'type_element' => 'tache',
				'nom_sql' => '',
				'taille_avant' => '0',
				'taille_libelle' => '0',
				'taille_champ' => '12',
				'taille_apres' => '0',
				'ordre' => '4',
				'type_champ' => '2',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '0',
				'nom_vue' => 'recurrence',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'formulaire_2_tache',
				'type_element' => 'tache',
				'nom_sql' => 'urgent',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '6',
				'taille_apres' => '4',
				'ordre' => '5',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'formulaire_2_tache',
				'type_element' => 'tache',
				'nom_sql' => 'client_id',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '6',
				'taille_apres' => '4',
				'ordre' => '6',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'formulaire_2_tache',
				'type_element' => 'tache',
				'nom_sql' => 'commentaire',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '10',
				'taille_apres' => '0',
				'ordre' => '7',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'formulaire_2_tache',
				'type_element' => 'tache',
				'nom_sql' => 'projet_id',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '6',
				'ordre' => '8',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'formulaire_2_tache',
				'type_element' => 'tache',
				'nom_sql' => 'ticket_client_id',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '6',
				'ordre' => '9',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'formulaire_2_tache',
				'type_element' => 'tache',
				'nom_sql' => 'prive',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '6',
				'ordre' => '10',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'formulaire_2_tache',
				'type_element' => 'tache',
				'nom_sql' => '',
				'taille_avant' => '0',
				'taille_libelle' => '0',
				'taille_champ' => '12',
				'taille_apres' => '0',
				'ordre' => '11',
				'type_champ' => '2',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '0',
				'nom_vue' => 'relance',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			],
	    ];