<?php
return [
    'type_element' => 'tache',
    'titre_formulaire' => 'Formulaire tache todo',
    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
        'surcharger_la_vue' => "1",
    ],
    'champs_libres' => [
        [
            'type_element' => "tache",
            'nom_sql' => "titre",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "6",
            'taille_apres' => "4",
            'ordre' => "1",
        ],
        [
            'type_element' => "tache",
            'nom_sql' => "type_tache_todo",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "6",
            'taille_apres' => "4",
            'ordre' => "2",
        ],
        [
            'type_element' => "tache",
            'nom_sql' => "date_de_debut",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "6",
            'taille_apres' => "4",
            'ordre' => "3",
        ],
        [
            'type_element' => "tache",
            'nom_sql' => "affectation",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "10",
            'taille_apres' => "0",
            'ordre' => "4",
        ],
        [
            'type_element' => "tache",
            'nom_sql' => "urgent",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "6",
            'taille_apres' => "4",
            'ordre' => "5",

        ],
        [
            'type_element' => "tache",
            'nom_sql' => "client_id",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "6",
            'taille_apres' => "4",
            'ordre' => "6",

        ],
        [
            'type_element' => "tache",
            'nom_sql' => "commentaire",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "10",
            'taille_apres' => "0",
            'ordre' => "7",

        ],
        [
            'type_element' => "tache",
            'nom_sql' => "projet_id",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "7",
            'condition_affichage_v_if' => '$root.type_element == \'projet\' || $root.type_element == \'ticket_client\' || (tache.projet_id != undefined && tache.projet_id != \'\')',

        ],
        [
            'type_element' => "tache",
            'nom_sql' => "ticket_client_id",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "8",
            'condition_affichage_v_if' => '$root.type_element == \'projet\' || $root.type_element == \'ticket_client\' || (tache.ticket_client_id != undefined && tache.ticket_client_id != \'\')',

        ],
        [
            'type_element' => 'tache',
            'nom_sql' => '',
            'taille_avant' => '0',
            'taille_libelle' => '0',
            'taille_champ' => '12',
            'taille_apres' => '0',
            'ordre' => '10',
            'type_champ' => '2',
            'nom_vue' => 'relance',
            'type_vue' => 'standard',
        ],
    ],
];