<?php return [

		        'vue_js' => [
		            'vuejs_data' => "",
		            'vuejs_methods' => "",
		            'surcharger_la_vue' => "",
                ],
                'champs_libres' => [
		[
			'nom_formulaire' => 'lead',
				'type_element' => 'lead',
				'nom_sql' => 'entreprise',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '6',
				'ordre' => '0',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'lead',
				'type_element' => 'lead',
				'nom_sql' => 'nom',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '1',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'lead',
				'type_element' => 'lead',
				'nom_sql' => 'prenom',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '2',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'lead',
				'type_element' => 'lead',
				'nom_sql' => 'telephone',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '3',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'lead',
				'type_element' => 'lead',
				'nom_sql' => 'adresse_email',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '4',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'lead',
				'type_element' => 'lead',
				'nom_sql' => 'responsable_commercial_id',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '5',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'lead',
				'type_element' => 'lead',
				'nom_sql' => 'note',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '6',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'lead',
				'type_element' => 'lead',
				'nom_sql' => 'etape',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '7',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'lead',
				'type_element' => 'lead',
				'nom_sql' => 'statut',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '8',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'lead',
				'type_element' => 'lead',
				'nom_sql' => 'source',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '0',
				'ordre' => '9',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			[
			'nom_formulaire' => 'lead',
				'type_element' => 'lead',
				'nom_sql' => 'commentaires',
				'taille_avant' => '0',
				'taille_libelle' => '12',
				'taille_champ' => '12',
				'taille_apres' => '0',
				'ordre' => '10',
				'type_champ' => '',
				'valeur_html' => '',
				'id_editeur' => '',
				'type_vue' => '',
				'nom_vue' => '',
				'condition_obligatoire' => '',
				'condition_lecture_seule' => '',
				'id_sous_formulaire' => '',
				'nom_sous_formulaire' => '',
				'nom_affichage_sous_formulaire' => '',
				
			],
			],
	    ];