<?php return [

    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
        'surcharger_la_vue' => "0",
    ],
    'champs_libres' => [
        [
            'nom_formulaire' => 'maquette',
            'type_element' => 'maquette',
            'nom_sql' => 'nom_application',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '0',
            'ordre' => '0',
        ],
        [
            'nom_formulaire' => 'maquette',
            'type_element' => 'maquette',
            'nom_sql' => 'logo_application',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '0',
            'ordre' => '1',
        ],
        [
            'nom_formulaire' => 'maquette',
            'type_element' => 'maquette',
            'nom_sql' => 'page_accueil',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '0',
            'ordre' => '2',
        ],
        [
            'nom_formulaire' => 'maquette',
            'type_element' => 'maquette',
            'nom_sql' => 'utilisation_logo_haut_gauche',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '0',
            'ordre' => '3',
        ],
        [
            'nom_formulaire' => 'maquette',
            'type_element' => 'maquette',
            'nom_sql' => 'devise_application_symbole',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '0',
            'ordre' => '4',
        ],
        [
            'nom_formulaire' => 'maquette',
            'type_element' => 'maquette',
            'nom_sql' => 'devise_application_iso',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '0',
            'ordre' => '5',
        ],
        [
            'nom_formulaire' => 'maquette',
            'type_element' => 'maquette',
            'nom_sql' => 'devise_application_nom',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '0',
            'ordre' => '6',
        ],
        [
            'nom_formulaire' => 'maquette',
            'type_element' => 'maquette',
            'nom_sql' => 'taille_police',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '0',
            'ordre' => '7',
        ],
        [
            'nom_formulaire' => 'maquette',
            'type_element' => 'maquette',
            'nom_sql' => 'poids_police',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '0',
            'ordre' => '8',
        ],
        [
            'nom_formulaire' => 'maquette',
            'type_element' => 'maquette',
            'nom_sql' => 'logo_application_connexion',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '0',
            'ordre' => '9',
        ],
        [
            'nom_formulaire' => 'maquette',
            'type_element' => 'maquette',
            'nom_sql' => 'langue_par_defaut',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '0',
            'ordre' => '10',
        ],
        [
            'nom_formulaire' => 'maquette',
            'type_element' => 'maquette',
            'nom_sql' => 'par_defaut',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '0',
            'ordre' => '11',
        ],
        [
            'nom_formulaire' => 'maquette',
            'type_element' => 'maquette',
            'nom_sql' => 'favicon',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '0',
            'ordre' => '12',
        ],
    ],
];