<?php
return [
    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
    ],
    'champs_libres' => [
        [
            'nom_formulaire' => "modele_email",
            'type_element' => "modele_email",
            'nom_sql' => "type_element_id",
            'taille_avant' => "0",
            'taille_libelle' => "4",
            'taille_champ' => "8",
            'taille_apres' => "0",
            'ordre' => "1",

        ],
        [
            'nom_formulaire' => "modele_email",
            'type_element' => "modele_email",
            'nom_sql' => "condition_affichage",
            'taille_avant' => "0",
            'taille_libelle' => "4",
            'taille_champ' => "8",
            'taille_apres' => "0",
            'ordre' => "2",

        ],
        [
            'nom_formulaire' => "modele_email",
            'type_element' => "modele_email",
            'nom_sql' => "categorie",
            'taille_avant' => "0",
            'taille_libelle' => "4",
            'taille_champ' => "8",
            'taille_apres' => "0",
            'ordre' => "3",

        ],
        [
            'nom_formulaire' => "modele_email",
            'type_element' => "modele_email",
            'nom_sql' => "langue",
            'taille_avant' => "0",
            'taille_libelle' => "4",
            'taille_champ' => "8",
            'taille_apres' => "0",
            'ordre' => "4",

        ],
        [
            'nom_formulaire' => "modele_email",
            'type_element' => "modele_email",
            'nom_sql' => "nom",
            'taille_avant' => "0",
            'taille_libelle' => "4",
            'taille_champ' => "8",
            'taille_apres' => "0",
            'ordre' => "5",

        ],
        [
            'nom_formulaire' => "modele_email",
            'type_element' => "modele_email",
            'nom_sql' => "enregistrer_echange",
            'taille_avant' => "0",
            'taille_libelle' => "4",
            'taille_champ' => "8",
            'taille_apres' => "0",
            'ordre' => "6",

        ],
        [
            'nom_formulaire' => 'modele_email',
            'type_element' => 'modele_email',
            'nom_sql' => 'utilisation_template_vide',
            'taille_avant' => '0',
            'taille_libelle' => '4',
            'taille_champ' => '8',
            'taille_apres' => '0',
            'ordre' => '7',

        ],
        [
            'nom_formulaire' => "modele_email",
            'type_element' => "modele_email",
            'nom_sql' => "",
            'ordre' => 8,
            'taille_avant' => 0,
            'taille_libelle' => 0,
            'taille_champ' => 12,
            'taille_apres' => 0,
            'type_champ' => 2,
            'nom_vue' => "champs_publipostages",
        ],
        [
            'nom_formulaire' => "modele_email",
            'type_element' => "modele_email",
            'nom_sql' => "",
            'ordre' => 9,
            'taille_avant' => 0,
            'taille_libelle' => 0,
            'taille_champ' => 12,
            'taille_apres' => 0,
            'type_champ' => 2,
            'nom_vue' => "regroupement_multiple",
        ],
         [
            'nom_formulaire' => 'modele_email',
            'type_element' => 'modele_email',
            'nom_sql' => '',
            'taille_avant' => '',
            'taille_libelle' => '',
            'taille_champ' => '',
            'taille_apres' => '',
            'ordre' => '10',
            'type_champ' => '3',
            'condition_affichage_v_if' => 'modele_email.type_element_id != null && modele_email.type_element_id != \'\' ',
            'nom_sous_formulaire' => 'modele_email_sous_formulaire_parametrage_destinataire_email',
            'nom_affichage_sous_formulaire' => 'Destinataire',
        ],
        [
            'nom_formulaire' => 'modele_email',
            'type_element' => 'modele_email',
            'nom_sql' => '',
            'taille_avant' => '',
            'taille_libelle' => '',
            'taille_champ' => '',
            'taille_apres' => '',
            'ordre' => '11',
            'type_champ' => '3',
            'condition_affichage_v_if' => 'modele_email.type_element_id != null && modele_email.type_element_id != \'\'',
            'nom_sous_formulaire' => 'modele_email_sous_formulaire_parametrage_piece_jointe_email',
            'nom_affichage_sous_formulaire' => 'Piéce jointe',
        ]
    ],
];
