<?php
return [
    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
    ],
    'champs_libres' => [
        [
            'nom_formulaire' => "modele_de_document",
            'type_element' => "modele_de_document",
            'nom_sql' => "nom",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "10",
            'taille_apres' => "0",
            'ordre' => "1",
        ],
        [
            'nom_formulaire' => "modele_de_document",
            'type_element' => "modele_de_document",
            'nom_sql' => "type_de_document",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "10",
            'taille_apres' => "0",
            'ordre' => "2",
        ],
        [
            'nom_formulaire' => "modele_de_document",
            'type_element' => "modele_de_document",
            'nom_sql' => "",
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => "3",
            'type_champ' => "2",
            'type_vue' => 'standard',
            'nom_vue' => 'type_element',
            'condition_affichage_v_if' => 'modele_de_document.type_de_document == 0',
        ],
        [
            'nom_formulaire' => "modele_de_document",
            'type_element' => "modele_de_document",
            'nom_sql' => "type_element_autres",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "10",
            'taille_apres' => "0",
            'ordre' => "4",
            'condition_affichage_v_if' => 'modele_de_document.type_de_document == 1',
        ],
        [
            'nom_formulaire' => "modele_de_document",
            'type_element' => "modele_de_document",
            'nom_sql' => "condition_affichage",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "10",
            'taille_apres' => "0",
            'ordre' => "5",
            'condition_affichage_v_if' => 'modele_de_document.type_de_document == 1',
        ],
        [
            'nom_formulaire' => "modele_de_document",
            'type_element' => "modele_de_document",
            'nom_sql' => "",
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => "6",
            'type_champ' => "2",
            'type_vue' => 'standard',
            'nom_vue' => 'nom_pdf_genere',
            'condition_affichage_v_if' => 'modele_de_document.type_de_document == 1',
        ],
        [
            'nom_formulaire' => "modele_de_document",
            'type_element' => "modele_de_document",
            'nom_sql' => "condition_enregistrement_dans_champ",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "10",
            'taille_apres' => "0",
            'ordre' => "7",
            'condition_affichage_v_if' => 'modele_de_document.type_de_document == 1',
        ],
        [
            'nom_formulaire' => "modele_de_document",
            'type_element' => "modele_de_document",
            'nom_sql' => "",
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => "8",
            'type_champ' => "2",
            'type_vue' => 'standard',
            'nom_vue' => 'champ_enregistrement',
            'condition_affichage_v_if' => "modele_de_document.type_de_document == 1",
        ],
        [
            'nom_formulaire' => "modele_de_document",
            'type_element' => "modele_de_document",
            'nom_sql' => "nom_vue",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "10",
            'taille_apres' => "0",
            'ordre' => "9",
        ],
        [
            'nom_formulaire' => "modele_de_document",
            'type_element' => "modele_de_document",
            'nom_sql' => "ordre",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "10",
        ],
        [
            'nom_formulaire' => "modele_de_document",
            'type_element' => "modele_de_document",
            'nom_sql' => "",
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "6",
            'taille_apres' => "0",
            'ordre' => "11",
            'type_champ' => "2",
            'type_vue' => 'standard',
            'nom_vue' => 'retirer_cgv_cga',
        ],
    ]
];