<?php return [

		        'vue_js' => [
		            'vuejs_data' => "",
		            'vuejs_methods' => "",
		            'surcharger_la_vue' => "",
                ],
                'champs_libres' => [
		[
			'nom_formulaire' => 'note_de_frais',
				'type_element' => 'note_de_frais',
				'nom_sql' => 'utilisateur_id',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '6',
				'ordre' => '0',
				
			],
			[
			'nom_formulaire' => 'note_de_frais',
				'type_element' => 'note_de_frais',
				'nom_sql' => 'client_id',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '6',
				'ordre' => '1',
				
			],
			[
			'nom_formulaire' => 'note_de_frais',
				'type_element' => 'note_de_frais',
				'nom_sql' => 'projet_id',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '6',
				'ordre' => '2',
				
			],
			[
			'nom_formulaire' => 'note_de_frais',
				'type_element' => 'note_de_frais',
				'nom_sql' => 'date',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '6',
				'ordre' => '3',
				
			],
			[
			'nom_formulaire' => 'note_de_frais',
				'type_element' => 'note_de_frais',
				'nom_sql' => 'montant_ht',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '6',
				'ordre' => '4',
				
			],
			[
			'nom_formulaire' => 'note_de_frais',
				'type_element' => 'note_de_frais',
				'nom_sql' => '',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '12',
				'taille_apres' => '0',
				'ordre' => '5',
				'type_champ' => '2',
				'nom_vue' => 'affichage_tva',
				
			],
			[
			'nom_formulaire' => 'note_de_frais',
				'type_element' => 'note_de_frais',
				'nom_sql' => 'montant_ttc',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '6',
				'ordre' => '6',
				
			],
			[
			'nom_formulaire' => 'note_de_frais',
				'type_element' => 'note_de_frais',
				'nom_sql' => 'montant_rembourse',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '4',
				'taille_apres' => '6',
				'ordre' => '7',
				
			],
			[
			'nom_formulaire' => 'note_de_frais',
				'type_element' => 'note_de_frais',
				'nom_sql' => 'commentaire',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '10',
				'taille_apres' => '0',
				'ordre' => '9',
				
			],
			[
				'nom_formulaire' => 'note_de_frais',
				'type_element' => 'note_de_frais',
				'nom_sql' => '',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '12',
				'taille_apres' => '0',
				'ordre' => '10',
				'type_champ' => '2',
				'nom_vue' => 'devise_etrangere',
	
			],
			[
			'nom_formulaire' => 'note_de_frais',
				'type_element' => 'note_de_frais',
				'nom_sql' => '',
				'taille_avant' => '0',
				'taille_libelle' => '2',
				'taille_champ' => '12',
				'taille_apres' => '0',
				'ordre' => '11',
				'type_champ' => '2',
				'nom_vue' => 'champ_image_reconaissance_automatique',
				
			],
			[
				'type_element' => 'note_de_frais',
				'nom_sql' => '',
				'taille_avant' => '',
				'taille_libelle' => '',
				'taille_champ' => '',
				'taille_apres' => '',
				'ordre' => 12,
				'type_champ' => 3,
				'nom_sous_formulaire' => 'note_de_frais_sous_formulaire_note_de_frais_lignes',
				'nom_affichage_sous_formulaire' => 'Lignes',
			],
	    ],
];