<?php return [

    'type_element' => 'note_de_frais',
    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
        'surcharger_la_vue' => "1",
    ],
    'champs_libres' => [
        [
            'nom_formulaire' => 'note_de_frais_formulaire',
            'type_element' => 'note_de_frais',
            'nom_sql' => 'client_id',
            'taille_avant' => '0',
            'taille_libelle' => '4',
            'taille_champ' => '8',
            'taille_apres' => '0',
            'ordre' => '0',
        ],
        [
            'nom_formulaire' => 'note_de_frais_formulaire',
            'type_element' => 'note_de_frais',
            'nom_sql' => 'date',
            'taille_avant' => '0',
            'taille_libelle' => '4',
            'taille_champ' => '8',
            'taille_apres' => '0',
            'ordre' => '1',
        ],
        [
            'nom_formulaire' => 'note_de_frais_formulaire',
            'type_element' => 'note_de_frais',
            'nom_sql' => 'utilisateur_id',
            'taille_avant' => '0',
            'taille_libelle' => '4',
            'taille_champ' => '8',
            'taille_apres' => '0',
            'ordre' => '2',
        ],
        [
            'nom_formulaire' => 'note_de_frais_formulaire',
            'type_element' => 'note_de_frais',
            'nom_sql' => 'projet_id',
            'taille_avant' => '0',
            'taille_libelle' => '4',
            'taille_champ' => '8',
            'taille_apres' => '0',
            'ordre' => '3',
        ],
        [
            'nom_formulaire' => 'note_de_frais_formulaire',
            'type_element' => 'note_de_frais',
            'nom_sql' => 'montant_ht',
            'taille_avant' => '0',
            'taille_libelle' => '4',
            'taille_champ' => '8',
            'taille_apres' => '0',
            'ordre' => '5',
        ],
        [
            'nom_formulaire' => 'note_de_frais_formulaire',
            'type_element' => 'note_de_frais',
            'nom_sql' => '',
            'taille_avant' => '0',
            'taille_libelle' => '0',
            'taille_champ' => '12',
            'taille_apres' => '0',
            'ordre' => '6',
            'type_champ' => '2',
            'nom_vue' => 'affichage_tva',
        ],
        [
            'nom_formulaire' => 'note_de_frais_formulaire',
            'type_element' => 'note_de_frais',
            'nom_sql' => 'montant_ttc',
            'taille_avant' => '0',
            'taille_libelle' => '4',
            'taille_champ' => '8',
            'taille_apres' => '0',
            'ordre' => '7',
        ],
        [
            'nom_formulaire' => 'note_de_frais_formulaire',
            'type_element' => 'note_de_frais',
            'nom_sql' => 'montant_rembourse',
            'taille_avant' => '0',
            'taille_libelle' => '4',
            'taille_champ' => '8',
            'taille_apres' => '0',
            'ordre' => '8',
        ],
        [
            'nom_formulaire' => 'note_de_frais_formulaire',
            'type_element' => 'note_de_frais',
            'nom_sql' => 'commentaire',
            'taille_avant' => '0',
            'taille_libelle' => '4',
            'taille_champ' => '8',
            'taille_apres' => '0',
            'ordre' => '10',
        ],
        [
            'nom_formulaire' => 'note_de_frais_formulaire',
            'type_element' => 'note_de_frais',
            'nom_sql' => 'article_id',
            'taille_avant' => '0',
            'taille_libelle' => '4',
            'taille_champ' => '8',
            'taille_apres' => '0',
            'ordre' => '4',
        ],
        [
            'nom_formulaire' => 'note_de_frais_formulaire',
            'type_element' => 'note_de_frais',
            'nom_sql' => 'cb_entreprise',
            'taille_avant' => '0',
            'taille_libelle' => '4',
            'taille_champ' => '8',
            'taille_apres' => '0',
            'ordre' => '9',
        ],
        [
            'nom_formulaire' => 'note_de_frais_formulaire',
            'type_element' => 'note_de_frais',
            'nom_sql' => 'responsable_id',
            'taille_avant' => '0',
            'taille_libelle' => '4',
            'taille_champ' => '8',
            'taille_apres' => '0',
            'ordre' => '11',
        ],
        [
            'nom_formulaire' => 'note_de_frais_formulaire',
            'type_element' => 'note_de_frais',
            'nom_sql' => 'pre_valide_dp',
            'taille_avant' => '0',
            'taille_libelle' => '4',
            'taille_champ' => '8',
            'taille_apres' => '0',
            'ordre' => '12',
        ],
        [
            'nom_formulaire' => 'note_de_frais_formulaire',
            'type_element' => 'note_de_frais',
            'nom_sql' => 'date_pre_validation',
            'taille_avant' => '0',
            'taille_libelle' => '4',
            'taille_champ' => '8',
            'taille_apres' => '0',
            'ordre' => '13',
        ],
        [
            'nom_formulaire' => 'note_de_frais_formulaire',
            'type_element' => 'note_de_frais',
            'nom_sql' => 'date_previ_remboursement',
            'taille_avant' => '0',
            'taille_libelle' => '4',
            'taille_champ' => '8',
            'taille_apres' => '0',
            'ordre' => '14',
        ],
    ],
];