<?php
return [
    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
        'surcharger_la_vue' => "",
    ],
    'champs_libres' => [
        [
            'nom_formulaire' => "notification_manuelle",
            'type_element' => 'notification_manuelle',
            'nom_sql' => 'titre',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "1",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
        ],
        [
            'nom_formulaire' => "notification_manuelle",
            'type_element' => 'notification_manuelle',
            'nom_sql' => 'type_notification',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "2",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
            'condition_lecture_seule' => "notification_manuelle.id > 0",
        ],
        [
            'nom_formulaire' => "notification_manuelle",
            'type_element' => 'notification_manuelle',
            'nom_sql' => 'type_element_id',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "3",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
            'condition_lecture_seule' => "notification_manuelle.id > 0",
        ],
        [
            'nom_formulaire' => "notification_manuelle",
            'type_element' => 'notification_manuelle',
            'nom_sql' => '',
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => "4",
            'type_champ' => 2,
            'valeur_html' => "",
            'id_editeur' => "",
            'nom_vue' => "choix_expediteur",
            'type_vue' => "standard",
            'condition_affichage_v_if' => 'notification_manuelle.type_notification == 2',
            'condition_obligatoire' => 'notification_manuelle.type_notification == 2',
        ],
        [
            'nom_formulaire' => "notification_manuelle",
            'type_element' => 'notification_manuelle',
            'nom_sql' => '',
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => "5",
            'type_champ' => 2,
            'valeur_html' => "",
            'id_editeur' => "",
            'nom_vue' => "contenu_notification",
            'type_vue' => "standard",
        ],
        [
            'nom_formulaire' => "notification_manuelle",
            'type_element' => 'notification_manuelle',
            'nom_sql' => 'condition',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "6",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
        ],
        [
            'nom_formulaire' => "notification_manuelle",
            'type_element' => 'notification_manuelle',
            'nom_sql' => 'condition_sql',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "10",
            'taille_apres' => "0",
            'ordre' => "7",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
            'condition_affichage_v_if' => "notification_manuelle.condition == 3",
            'condition_obligatoire' => "notification_manuelle.condition == 3",
        ],
        [
            'nom_formulaire' => 'notification_manuelle',
            'type_element' => 'notification_manuelle',
            'nom_sql' => '',
            'taille_avant' => '',
            'taille_libelle' => '',
            'taille_champ' => '',
            'taille_apres' => '',
            'ordre' => '8',
            'type_champ' => '3',
            'condition_affichage_v_if' => 'notification_manuelle.type_element_id != null && notification_manuelle.type_element_id != \'\' && notification_manuelle.type_notification == 1',
            'nom_sous_formulaire' => 'notification_manuelle_sous_formulaire_parametrage_destinataire_erp',
            'nom_affichage_sous_formulaire' => 'Destinataire',
        ],
        [
            'nom_formulaire' => 'notification_manuelle',
            'type_element' => 'notification_manuelle',
            'nom_sql' => '',
            'taille_avant' => '',
            'taille_libelle' => '',
            'taille_champ' => '',
            'taille_apres' => '',
            'ordre' => '9',
            'type_champ' => '3',
            'condition_affichage_v_if' => 'notification_manuelle.type_element_id != null && notification_manuelle.type_element_id != \'\'  && notification_manuelle.type_notification == 2',
            'nom_sous_formulaire' => 'notification_manuelle_sous_formulaire_parametrage_destinataire_email',
            'nom_affichage_sous_formulaire' => 'Destinataire',
        ],
        [
            'nom_formulaire' => 'notification_manuelle',
            'type_element' => 'notification_manuelle',
            'nom_sql' => '',
            'taille_avant' => '',
            'taille_libelle' => '',
            'taille_champ' => '',
            'taille_apres' => '',
            'ordre' => '10',
            'type_champ' => '3',
            'condition_affichage_v_if' => 'notification_manuelle.type_element_id != null && notification_manuelle.type_element_id != \'\'  && notification_manuelle.type_notification == 2',
            'nom_sous_formulaire' => 'notification_manuelle_sous_formulaire_parametrage_piece_jointe_email',
            'nom_affichage_sous_formulaire' => 'Piéce jointe',
        ]
    ],
];