<?php
return [
    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
        'surcharger_la_vue' => "",
    ],
    'champs_libres' => [
        [
            'nom_formulaire' => "parametrage_balise_publipostage",
            'type_element' => 'parametrage_balise_publipostage',
            'nom_sql' => 'type_element_id',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "1",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
        ],
        [
            'nom_formulaire' => "parametrage_balise_publipostage",
            'type_element' => 'parametrage_balise_publipostage',
            'nom_sql' => 'nom',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "2",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
        ],
        [
            'nom_formulaire' => "parametrage_balise_publipostage",
            'type_element' => 'parametrage_balise_publipostage',
            'nom_sql' => '',
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => "3",
            'type_champ' => 2,
            'valeur_html' => "",
            'id_editeur' => "",
            'nom_vue' => "parametrage",
            'type_vue' => "standard",
        ],
    ]
];