<?php
return [
    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
        'surcharger_la_vue' => "",
    ],
    'champs_libres' => [
        [
            'nom_formulaire' => "parametrage_destinataire_email",
            'type_element' => 'parametrage_destinataire_email',
            'nom_sql' => 'type_element_id',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "1",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
            'condition_affichage_v_if' => '!sous_formulaire && !(parametrage_destinataire_email.modele_email_id > 0) && !(parametrage_destinataire_email.notification_manuelle_id > 0)'
        ],
        [
            'nom_formulaire' => "parametrage_destinataire_email",
            'type_element' => 'parametrage_destinataire_email',
            'nom_sql' => 'modele_email_id',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "2",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
            'condition_affichage_v_if' => '!sous_formulaire && !(parametrage_destinataire_email.type_element_id > 0) && !(parametrage_destinataire_email.notification_manuelle_id > 0)'
        ],
        [
            'nom_formulaire' => "parametrage_destinataire_email",
            'type_element' => 'parametrage_destinataire_email',
            'nom_sql' => 'notification_manuelle_id',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "3",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
            'condition_affichage_v_if' => '!sous_formulaire && !(parametrage_destinataire_email.type_element_id > 0) && !(parametrage_destinataire_email.modele_email_id > 0)'
        ],
        [
            'nom_formulaire' => "parametrage_destinataire_email",
            'type_element' => 'parametrage_destinataire_email',
            'nom_sql' => 'niveau',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "4",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
            'condition_affichage_v_if' => '(parametrage_destinataire_email.parametrage_existant == null || parametrage_destinataire_email.parametrage_existant == \'\') && !(parametrage_destinataire_email.notification_manuelle_id > 0)',
            'condition_obligatoire' => '(parametrage_destinataire_email.parametrage_existant == null || parametrage_destinataire_email.parametrage_existant == \'\') && !(parametrage_destinataire_email.notification_manuelle_id > 0)'
        ],
        [
            'nom_formulaire' => "parametrage_destinataire_email",
            'type_element' => 'parametrage_destinataire_email',
            'nom_sql' => 'type',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "5",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
            'condition_affichage_v_if' => '(parametrage_destinataire_email.parametrage_existant == null || parametrage_destinataire_email.parametrage_existant == \'\') && parametrage_destinataire_email.niveau > 1'
        ],
        [
            'nom_formulaire' => "parametrage_destinataire_email",
            'type_element' => 'parametrage_destinataire_email',
            'nom_sql' => '',
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => "6",
            'type_champ' => 2,
            'valeur_html' => "",
            'id_editeur' => "",
            'nom_vue' => "destinataire",
            'type_vue' => "standard",
        ],
        [
            'nom_formulaire' => "parametrage_destinataire_email",
            'type_element' => 'parametrage_destinataire_email',
            'nom_sql' => 'nom_simplifie',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "7",
            'type_champ' => "",
            'valeur_html' => "",
            'id_editeur' => "",
            'condition_affichage_v_if' => 'parametrage_destinataire_email.lien_champ != null && parametrage_destinataire_email.lien_champ != \'\''
        ],
    ]
];