<?php
return [
    'type_element' => "utilisateur",
    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
        'type_element' => 'utilisateur',
    ],
    'champs_libres' => [
        [
            'nom_formulaire' => "preferences",
            'type_element' => "utilisateur",
            'nom_sql' => "",
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => "1",
            'type_champ' => "1",
            'valeur_html' => "<div class='row'><div class='col-sm-12 css_form_ligne_titre'>" . traduction_blade('interface.gestion_utilisateur_connecte.titre_module.informations') . "</div></div>",
        ],
        [
            'nom_formulaire' => "preferences",
            'type_element' => "utilisateur",
            'nom_sql' => "nom",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "2",
            'obligatoire' => 1,

        ],
        [
            'nom_formulaire' => "preferences",
            'type_element' => "utilisateur",
            'nom_sql' => "prenom",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "3",
            'obligatoire' => 1,

        ],
        [
            'nom_formulaire' => "preferences",
            'type_element' => "utilisateur",
            'nom_sql' => "telephone",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "4",
        ],
        [
            'nom_formulaire' => "preferences",
            'type_element' => "utilisateur",
            'nom_sql' => "",
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "2",
            'taille_apres' => "0",
            'ordre' => "5",
            'type_champ' => "1",
            'valeur_html' => traduction_blade('champs_libres.utilisateur.langue.nom'),
        ],
        [
            'nom_formulaire' => "preferences",
            'type_element' => "utilisateur",
            'nom_sql' => "",
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "6",
            'type_champ' => "2",
            'valeur_html' => "",
            'nom_vue' => "langue",
            'type_vue' => "standard",
        ],
        [
            'nom_formulaire' => "preferences",
            'type_element' => "utilisateur",
            'nom_sql' => "",
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => "7",
            'type_champ' => "1",
            'valeur_html' => "<div class='row'><div class='col-sm-12 css_form_ligne_titre'>" . traduction_blade('interface.gestion_utilisateur_connecte.titre_module.changer_de_mot_de_passe') . "</div></div>",
        ],
        [
            'nom_formulaire' => "preferences",
            'type_element' => "utilisateur",
            'nom_sql' => "mot_de_passe",
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => "8",
        ],
        [
            'nom_formulaire' => "preferences",
            'type_element' => "utilisateur",
            'nom_sql' => "double_facteur_authentification",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "9",
        ],
        [
            'nom_formulaire' => "preferences",
            'type_element' => "utilisateur",
            'nom_sql' => "",
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => "10",
            'type_champ' => "1",
            'valeur_html' => "<div class='row'><div class='col-sm-12 css_form_ligne_titre'>" . traduction_blade('interface.gestion_utilisateur_connecte.titre_categorie.changer_avatar') . "</div></div>",
        ],
        [
            'nom_formulaire' => "preferences",
            'type_element' => "utilisateur",
            'nom_sql' => "avatar",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "11",
        ],
    ]
];