<?php
    return [
        'vue_js' => [
            'vuejs_data' => "",
            'vuejs_methods' => "",
        ],
        'champs_libres' => [
            [
                'nom_formulaire' => 'profil_droits_element',
                'type_element' => 'profil_droits_element',
                'nom_sql' => 'profil_id',
                'taille_avant' => '0',
                'taille_libelle' => '2',
                'taille_champ' => '4',
                'taille_apres' => '0',
                'ordre' => '1',
            ],
            [
                'nom_formulaire' => 'profil_droits_element',
                'type_element' => 'profil_droits_element',
                'nom_sql' => '',
                'taille_avant' => '0',
                'taille_libelle' => '0',
                'taille_champ' => '12',
                'taille_apres' => '0',
                'type_champ' => "2",
                'nom_vue' => 'gestion_element',
                'type_vue' => 'standard',
                'condition_affichage_v_if' => '1',
                'ordre' => '2',

            ],
            [
                'nom_formulaire' => 'profil_droits_element',
                'type_element' => 'profil_droits_element',
                'nom_sql' => 'entite_id',
                'taille_avant' => '0',
                'taille_libelle' => '2',
                'taille_champ' => '4',
                'taille_apres' => '6',
                'ordre' => '3',
            ],
            [
                'nom_formulaire' => 'profil_droits_element',
                'type_element' => 'profil_droits_element',
                'nom_sql' => 'lecture',
                'taille_avant' => '0',
                'taille_libelle' => '2',
                'taille_champ' => '4',
                'taille_apres' => '0',
                'ordre' => '4',
            ],
            [
                'nom_formulaire' => 'profil_droits_element',
                'type_element' => 'profil_droits_element',
                'nom_sql' => 'creation',
                'taille_avant' => '0',
                'taille_libelle' => '2',
                'taille_champ' => '4',
                'taille_apres' => '0',
                'ordre' => '5',
                'condition_affichage_v_if' => 'profil_droits_element.nom_sql == \'\' || profil_droits_element.nom_sql == null',
            ],
            [
                'nom_formulaire' => 'profil_droits_element',
                'type_element' => 'profil_droits_element',
                'nom_sql' => 'modification',
                'taille_avant' => '0',
                'taille_libelle' => '2',
                'taille_champ' => '4',
                'taille_apres' => '0',
                'ordre' => '6',
            ],
            [
                'nom_formulaire' => 'profil_droits_element',
                'type_element' => 'profil_droits_element',
                'nom_sql' => 'suppression',
                'taille_avant' => '0',
                'taille_libelle' => '2',
                'taille_champ' => '4',
                'taille_apres' => '0',
                'ordre' => '7',
            ],
            [
                'nom_formulaire' => 'profil_droits_element',
                'type_element' => 'profil_droits_element',
                'nom_sql' => 'modification_en_masse',
                'taille_avant' => '0',
                'taille_libelle' => '2',
                'taille_champ' => '4',
                'taille_apres' => '0',
                'ordre' => '8',
                'condition_affichage_v_if' => 'profil_droits_element.nom_sql == \'\' || profil_droits_element.nom_sql == null',
            ],
            [
                'nom_formulaire' => 'profil_droits_element',
                'type_element' => 'profil_droits_element',
                'nom_sql' => 'suppression_en_masse',
                'taille_avant' => '0',
                'taille_libelle' => '2',
                'taille_champ' => '4',
                'taille_apres' => '0',
                'ordre' => '9',
                'condition_affichage_v_if' => 'profil_droits_element.nom_sql == \'\' || profil_droits_element.nom_sql == null',
            ],
            [
                'nom_formulaire' => 'profil_droits_element',
                'type_element' => 'profil_droits_element',
                'nom_sql' => 'comptabilisation',
                'taille_avant' => '0',
                'taille_libelle' => '2',
                'taille_champ' => '4',
                'taille_apres' => '0',
                'ordre' => '10',
                'condition_affichage_v_if' => "['note_de_frais','facture_vente','facture_achat','acompte_vente','acompte_achat','avoir_vente','avoir_achat'].includes(profil_droits_element.type_element)",
            ],
        ],
    ];