<?php return [

    'type_element' => 'tache',
    'titre_formulaire' => 'Formulaire participant rdv',
    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
        'surcharger_la_vue' => "1",
    ],
    'champs_libres' => [
        [
            'nom_formulaire' => 'tache_formulaire_participants',
            'type_element' => 'tache',
            'nom_sql' => 'titre',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '6',
            'taille_apres' => '4',
            'ordre' => '0',

        ],
        [
            'nom_formulaire' => 'tache_formulaire_participants',
            'type_element' => 'tache',
            'nom_sql' => 'type_tache_rdv',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '6',
            'taille_apres' => '4',
            'ordre' => '1',
            'condition_lecture_seule' => '1',
        ],
        [
            'nom_formulaire' => 'tache_formulaire_participants',
            'type_element' => 'tache',
            'nom_sql' => '',
            'taille_avant' => '0',
            'taille_libelle' => '0',
            'taille_champ' => '12',
            'taille_apres' => '0',
            'ordre' => '2',
            'type_champ' => '2',
            'type_vue' => '0',
            'nom_vue' => 'dates',
        ],
        [
            'nom_formulaire' => 'tache_formulaire_participants',
            'type_element' => 'tache',
            'nom_sql' => '',
            'taille_avant' => '0',
            'taille_libelle' => '0',
            'taille_champ' => '12',
            'taille_apres' => '0',
            'ordre' => '4',
            'type_champ' => '2',
            'type_vue' => '0',
            'nom_vue' => 'participants',
        ],
        [
            'nom_formulaire' => 'tache_formulaire_participants',
            'type_element' => 'tache',
            'nom_sql' => '',
            'taille_avant' => '0',
            'taille_libelle' => '0',
            'taille_champ' => '12',
            'taille_apres' => '0',
            'ordre' => '5',
            'type_champ' => '2',
            'type_vue' => '0',
            'nom_vue' => 'recurrence',
        ],
        [
            'nom_formulaire' => 'tache_formulaire_participants',
            'type_element' => 'tache',
            'nom_sql' => 'urgent',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '6',
            'taille_apres' => '4',
            'ordre' => '6',
        ],
        [
            'nom_formulaire' => 'tache_formulaire_participants',
            'type_element' => 'tache',
            'nom_sql' => 'client_id',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '6',
            'taille_apres' => '4',
            'ordre' => '7',
            'condition_obligatoire' => '',
            'condition_lecture_seule' => '1',
        ],
        [
            'nom_formulaire' => 'tache_formulaire_participants',
            'type_element' => 'tache',
            'nom_sql' => 'commentaire',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '10',
            'taille_apres' => '0',
            'ordre' => '8',
            'condition_obligatoire' => '',
            'condition_lecture_seule' => '',
        ],
        [
            'nom_formulaire' => 'tache_formulaire_participants',
            'type_element' => 'tache',
            'nom_sql' => 'projet_id',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '6',
            'ordre' => '9',
            'condition_obligatoire' => '',
            'condition_lecture_seule' => '1',

        ],
        [
            'nom_formulaire' => 'tache_formulaire_participants',
            'type_element' => 'tache',
            'nom_sql' => 'ticket_client_id',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '6',
            'ordre' => '10',
            'condition_obligatoire' => '',
            'condition_lecture_seule' => '1',

        ],
        [
            'nom_formulaire' => 'tache_formulaire_participants',
            'type_element' => 'tache',
            'nom_sql' => 'prive',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '6',
            'ordre' => '11',
            'condition_obligatoire' => '',
            'condition_lecture_seule' => '',
        ],
        [
            'nom_formulaire' => 'tache_formulaire_participants',
            'type_element' => 'tache',
            'nom_sql' => '',
            'taille_avant' => '0',
            'taille_libelle' => '0',
            'taille_champ' => '12',
            'taille_apres' => '0',
            'ordre' => '12',
            'type_champ' => '2',
            'type_vue' => '0',
            'nom_vue' => 'relance',
        ],
    ],
];