<?php return [

    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
        'surcharger_la_vue' => "0",
    ],
    'champs_libres' => [
        [
            'nom_formulaire' => 'tache_erreurs_synchro_externe',
            'type_element' => 'tache_erreurs_synchro_externe',
            'nom_sql' => 'id_externe',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '10',
            'taille_apres' => '0',
            'ordre' => '1',
            'condition_lecture_seule' => '1',
        ],
        [
            'nom_formulaire' => 'tache_erreurs_synchro_externe',
            'type_element' => 'tache_erreurs_synchro_externe',
            'nom_sql' => 'utilisateur',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '4',
            'taille_apres' => '6',
            'ordre' => '2',
            'condition_lecture_seule' => '1',
        ],
        [
            'nom_formulaire' => 'tache_erreurs_synchro_externe',
            'type_element' => 'tache_erreurs_synchro_externe',
            'nom_sql' => 'message_erreur',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '10',
            'taille_apres' => '0',
            'ordre' => '3',
            'condition_lecture_seule' => '1',
        ],
        [
            'nom_formulaire' => 'tache_erreurs_synchro_externe',
            'type_element' => 'tache_erreurs_synchro_externe',
            'nom_sql' => 'stacktrace_erreur',
            'taille_avant' => '0',
            'taille_libelle' => '2',
            'taille_champ' => '10',
            'taille_apres' => '0',
            'ordre' => '4',
            'condition_lecture_seule' => '1',
        ],
        [
            'nom_formulaire' => 'tache_erreurs_synchro_externe',
            'type_element' => 'tache_erreurs_synchro_externe',
            'nom_sql' => 'modele_rdv',
            'taille_avant' => '0',
            'taille_libelle' => '12',
            'taille_champ' => '12',
            'taille_apres' => '0',
            'ordre' => '5',
            'condition_lecture_seule' => '1',
        ],
        [
            'nom_formulaire' => 'tache_erreurs_synchro_externe',
            'type_element' => 'tache_erreurs_synchro_externe',
            'nom_sql' => 'synchro_externe',
            'taille_avant' => '0',
            'taille_libelle' => '12',
            'taille_champ' => '12',
            'taille_apres' => '0',
            'ordre' => '6',
            'condition_lecture_seule' => '1',
        ],
    ],
];