<?php
return [
    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
    ],
    'champs_libres' => [
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "",
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => "1",
            'type_champ' => "1",
            'valeur_html' => "<div class='row'><div class='col-sm-12 css_form_ligne_titre'>" . traduction_blade('formulaire.divers.informations_generales') . "</div></div>",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "",
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => "2",
            'type_champ' => "2",
            'nom_vue' => "type_utilisateur",
            'type_vue' => "standard",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "droit_usurpation",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "3",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur == 1",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "autorise_a_se_connecter",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "4",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => '',
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => '5',
            'type_champ' => "2",
            'nom_vue' => "accueil",
            'type_vue' => "standard",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "prenom",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "6",
            'obligatoire' => 1,

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "nom",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "7",
            'obligatoire' => 1,

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "email",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "8",
            'condition_obligatoire' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "telephone",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "9",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "mot_de_passe",
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => "10",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "avatar",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "11",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "",
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => "12",
            'type_champ' => "2",
            'valeur_html' => "",
            'nom_vue' => "licence",
            'type_vue' => "standard",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur < 2 && utilisateur.autorise_a_se_connecter != 0",
        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "equipe",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "13",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "couleur_fond_tache",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "14",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "couleur_police_tache",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "15",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "validation_conges_n_plus_1",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "16",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "validation_conges_n_plus_2",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "17",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "validation_ndf_n_plus_1",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "16",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "validation_ndf_n_plus_2",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "17",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "validation_saisie_temps",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "18",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "validation_jours_travailles",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "18",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "gestion_ticket",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "19",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "cacher_acces_support",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "20",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur == 2",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "autorisation_intranet",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "22",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "matricule",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "23",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "lien_linkedin",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "24",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "titre",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "25",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "synchronisation_calendrier_outlook",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "26",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],

        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "date_derniere_synchro_rdv_microsoft",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "27",
            'condition_affichage_v_if' => "utilisateur.synchronisation_calendrier_outlook",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "synchronisation_calendrier_google",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "26",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "date_derniere_synchro_rdv_google",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "27",
            'condition_affichage_v_if' => "utilisateur.synchronisation_calendrier_google",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "date_derniere_connexion",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "27",
            'condition_affichage_v_if' => "",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "restrictions_erp",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "28",
            'condition_affichage_v_if' => "",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "type_contrat",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "29",
            'condition_affichage_v_if' => "",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "quantite_contrat",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "30",
            'condition_affichage_v_if' => "",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "code_analytique",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "31",
            'condition_affichage_v_if' => "",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "",
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => "32",
            'type_champ' => "1",
            'valeur_html' => "<div class='row'><div class='col-sm-12 css_form_ligne_titre'>" . traduction_blade('interface.gestion_utilisateurs.modale_utilisateurs.titre_categorie.profil') . "</div></div>",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "profil_id",
            'taille_avant' => "0",
            'taille_libelle' => "3",
            'taille_champ' => "9",
            'taille_apres' => "0",
            'ordre' => "33",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "maquette_id",
            'taille_avant' => "0",
            'taille_libelle' => "3",
            'taille_champ' => "9",
            'taille_apres' => "0",
            'ordre' => "34",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => '',
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => '35',
            'type_champ' => "2",
            'nom_vue' => "entite",
            'type_vue' => "standard",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",

        ],
        [
            'nom_formulaire' => "utilisateur",
            'type_element' => "utilisateur",
            'nom_sql' => "entite_id_defaut",
            'taille_avant' => "0",
            'taille_libelle' => "3",
            'taille_champ' => "9",
            'taille_apres' => "0",
            'ordre' => "36",
            'condition_affichage_v_if' => "utilisateur.type_utilisateur != 3",
        ],
    ],
];
