<?php
return [
    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
    ],
    'champs_libres' => [
        [
            'nom_formulaire' => "utilisateur_extranet",
            'type_element' => "utilisateur_extranet",
            'nom_sql' => "",
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => "0",
            'type_champ' => "2",
            'valeur_html' => "",
            'nom_vue' => "boutons",
            'type_vue' => "standard",
        ],
        [
            'nom_formulaire' => "utilisateur_extranet",
            'type_element' => "utilisateur_extranet",
            'nom_sql' => "email",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "6",
            'ordre' => "1"
        ],
        [
            'nom_formulaire' => 'utilisateur_extranet',
            'type_element' => 'utilisateur_extranet',
            'nom_sql' => 'Intégration bloc html 1',
            'taille_avant' => '0',
            'taille_libelle' => '0',
            'taille_champ' => '12',
            'taille_apres' => '0',
            'ordre' => '2',
            'type_champ' => '1',
            'condition_affichage_v_if' => '!(utilisateur_extranet.id > 0)',
            'valeur_html' => '<div class="row"><div class="col-sm-12">{{ this.$root.traduction(\'formulaire.utilisateur_extranet.message_envoi_mail\')}}</div></div>',
        ],
        [
            'nom_formulaire' => "utilisateur_extranet",
            'type_element' => "utilisateur_extranet",
            'nom_sql' => "nom",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "3"
        ],
        [
            'nom_formulaire' => "utilisateur_extranet",
            'type_element' => "utilisateur_extranet",
            'nom_sql' => "prenom",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "4"
        ],
        [
            'nom_formulaire' => "utilisateur_extranet",
            'type_element' => "utilisateur_extranet",
            'nom_sql' => "profil",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "5",

        ],
        [
            'nom_formulaire' => "utilisateur_extranet",
            'type_element' => "utilisateur_extranet",
            'nom_sql' => "langue",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "6",

        ],
        [
            'nom_formulaire' => "utilisateur_extranet",
            'type_element' => "utilisateur_extranet",
            'nom_sql' => "autorise_a_se_connecter",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "7",

        ],
        [
            'nom_formulaire' => "utilisateur_extranet",
            'type_element' => "utilisateur_extranet",
            'nom_sql' => "admin",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "8",

        ],
        [
            'nom_formulaire' => "utilisateur_extranet",
            'type_element' => "utilisateur_extranet",
            'nom_sql' => "renouveler_mot_de_passe",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "9",

        ],
        [
            'nom_formulaire' => "utilisateur_extranet",
            'type_element' => "utilisateur_extranet",
            'nom_sql' => "derniere_connexion",
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "10",

        ],
        [
            'nom_formulaire' => "utilisateur_extranet",
            'type_element' => "utilisateur_extranet",
            'nom_sql' => "",
            'taille_avant' => "0",
            'taille_libelle' => "0",
            'taille_champ' => "12",
            'taille_apres' => "0",
            'ordre' => "11",
            'type_champ' => "2",
            'valeur_html' => "",
            'nom_vue' => "contacts",
            'type_vue' => "standard",
        ],
    ],
];
