<?php
return [
    'vue_js' => [
        'vuejs_data' => "",
        'vuejs_methods' => "",
        'surcharger_la_vue' => "",
    ],
    'champs_libres' => [
        [
			'nom_formulaire' => 'vue_sql',
            'type_element' => 'vue_sql',
            'nom_sql' => '',
            'taille_avant' => '0',
            'taille_libelle' => '0',
            'taille_champ' => '12',
            'taille_apres' => '0',
            'ordre' => '2',
            'type_champ' => '2',
            'type_vue' => '0',
            'nom_vue' => 'nom',
        ],
        [
            'nom_formulaire' => "vue_sql",
            'type_element' => 'vue_sql',
            'nom_sql' => 'type_de_vue',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "2",
        ],
        [
            'nom_formulaire' => "vue_sql",
            'type_element' => 'vue_sql',
            'nom_sql' => 'table_par_defaut',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "3",
            'condition_affichage_v_if' => 'vue_sql.type_de_vue == 1',
        ],
        [
            'nom_formulaire' => "vue_sql",
            'type_element' => 'vue_sql',
            'nom_sql' => 'tables',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "4",
            'condition_affichage_v_if' => 'vue_sql.type_de_vue == 0',
        ],
        [
            'nom_formulaire' => "vue_sql",
            'type_element' => 'vue_sql',
            'nom_sql' => 'alias_tables',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "4",
            'condition_affichage_v_if' => 'vue_sql.type_de_vue == 0',
        ],
        [
            'nom_formulaire' => "vue_sql",
            'type_element' => 'vue_sql',
            'nom_sql' => 'joins',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "4",
            'taille_apres' => "0",
            'ordre' => "3",
            'condition_affichage_v_if' => 'vue_sql.type_de_vue == 0',
        ],
        [
            'nom_formulaire' => "vue_sql",
            'type_element' => 'vue_sql',
            'nom_sql' => 'autres_conditions',
            'taille_avant' => "0",
            'taille_libelle' => "2",
            'taille_champ' => "10",
            'taille_apres' => "0",
            'ordre' => "5",
            'condition_affichage_v_if' => 'vue_sql.type_de_vue == 0',
        ],
    ],
];